import type { ContentBlock, GlossaryTerm } from "@/lib/types";

export interface DeepTopicProfile {
  estimatedMinutes: number;
  objectives: string[];
  glossary: GlossaryTerm[];
  sourceIds: string[];
  content: ContentBlock[];
}

const complexity: DeepTopicProfile = {
  estimatedMinutes: 95,
  sourceIds: ["clrs-4e"],
  objectives: [
    "Distinguish input size from the numeric value of an input.",
    "Count dominant operations for iterative and recursive procedures.",
    "Use O, Ω, and Θ with their correct mathematical meaning.",
    "Separate worst-case, average-case, expected, and amortized analysis.",
    "Compare growth rates while ignoring only constants and lower-order terms.",
    "Recognize when a complexity claim hides an important model assumption.",
  ],
  glossary: [
    { term: "Input size", definition: "A measure of how much information an input contains, commonly the number of elements or bits needed to encode it." },
    { term: "Asymptotic bound", definition: "A statement about growth after some sufficiently large input size, independent of machine-specific constant factors." },
    { term: "Amortized cost", definition: "The average cost per operation over a worst-case sequence of operations, without assuming a probability distribution." },
  ],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Learning objectives", objectives: ["Model cost as a function of input size", "Prove simple asymptotic bounds", "Analyze loops, recursion, and operation sequences", "Communicate assumptions behind a complexity result"] },
    { type: "intuition", id: "intuition", title: "Why growth matters", body: "Runtime in milliseconds is tied to one machine and one input. Complexity analysis asks a more durable question: how quickly does the required work grow when the problem becomes larger? A 100× faster computer cannot rescue an exponential algorithm for long, while a linear algorithm usually scales predictably.", analogy: "Complexity is the shape of a cost curve, not a stopwatch reading." },
    { type: "definition", id: "cost-model", title: "Choose a cost model", term: "RAM model", definition: "A simplified machine model in which primitive arithmetic, comparisons, assignments, and indexed memory accesses take constant time. The model is useful only when its assumptions match the problem scale.", notation: "T(n): number of primitive operations on an input of size n", citations: [{ sourceId: "clrs-4e", locator: "Chapter 2" }] },
    { type: "formula", id: "asymptotic-notation", title: "Asymptotic notation", expression: "0 ≤ c₁g(n) ≤ f(n) ≤ c₂g(n), for every n ≥ n₀", description: "This inequality defines f(n) ∈ Θ(g(n)). Big-O keeps only the upper inequality; Ω keeps only the lower inequality.", terms: [{ symbol: "f(n)", meaning: "The cost being analyzed" }, { symbol: "g(n)", meaning: "The comparison growth function" }, { symbol: "c₁, c₂", meaning: "Positive constant factors" }, { symbol: "n₀", meaning: "The threshold after which the bound holds" }], citations: [{ sourceId: "clrs-4e", locator: "Chapter 3" }] },
    { type: "worked-example", id: "loop-example", title: "Worked example: triangular loop", problem: "Analyze a nested loop where the inner loop runs from 0 through i for every i from 0 through n − 1.", steps: [{ title: "Count inner iterations", explanation: "For a fixed i, the inner body executes i + 1 times.", formula: "1 + 2 + ⋯ + n" }, { title: "Evaluate the sum", explanation: "The arithmetic-series identity gives an exact count.", formula: "n(n + 1) / 2 = n²/2 + n/2" }, { title: "Extract the growth rate", explanation: "The n² term dominates; constant coefficients and the lower-order n term do not change the asymptotic class.", formula: "T(n) ∈ Θ(n²)" }], conclusion: "The loops are not Θ(n²) merely because there are two of them; the conclusion follows from the total iteration count." },
    { type: "worked-example", id: "binary-example", title: "Worked example: repeated halving", problem: "A loop repeatedly replaces n by floor(n / 2) until n becomes 1. How many iterations execute?", steps: [{ title: "Write the state after k steps", explanation: "Ignoring flooring for the bound, the remaining value is n / 2ᵏ.", formula: "nₖ ≈ n / 2ᵏ" }, { title: "Solve the stopping condition", explanation: "The loop stops when the remaining value is at most 1.", formula: "n / 2ᵏ ≤ 1 ⇒ 2ᵏ ≥ n" }, { title: "Apply logarithms", explanation: "The smallest suitable k is the ceiling of log base 2 of n.", formula: "k = ⌈log₂ n⌉" }], conclusion: "Repeated multiplication or division by a constant usually produces logarithmic depth." },
    { type: "key-idea", id: "analysis-method", title: "A repeatable analysis method", body: "Analyze the algorithm from its control structure and invariant, not from a memorized label.", points: ["Define the input-size variable precisely.", "Choose the operation or resource to count.", "Express the count as a sum or recurrence.", "Solve or bound that expression.", "State the case being analyzed and any machine-model assumptions."] },
    { type: "comparison", id: "growth-comparison", title: "Growth-rate landmarks", columns: ["Growth", "Typical interpretation", "Scaling behavior"], rows: [{ label: "Θ(1)", values: ["Direct access or bounded work", "Unaffected by n in the model"] }, { label: "Θ(log n)", values: ["Repeatedly shrink by a constant factor", "Adds one step when n doubles"] }, { label: "Θ(n)", values: ["Inspect every item once", "Doubles when n doubles"] }, { label: "Θ(n log n)", values: ["Balanced divide and combine", "Near-linear for practical sizes"] }, { label: "Θ(n²)", values: ["All pairs or nested scans", "Quadruples when n doubles"] }, { label: "Θ(2ⁿ)", values: ["Enumerate subsets", "Becomes infeasible rapidly"] }] },
    { type: "complexity", id: "cases", title: "Cases and aggregate cost", time: "Depends on the algorithm and selected case", space: "Auxiliary space excludes the input unless stated otherwise", analysis: "Worst-case bounds are guarantees, average-case bounds require an input distribution, expected bounds may arise from randomized choices, and amortized bounds cover a complete operation sequence.", cases: [{ name: "Worst case", complexity: "max over inputs of size n", reason: "Provides a guarantee" }, { name: "Average case", complexity: "expectation over inputs", reason: "Requires a stated distribution" }, { name: "Amortized", complexity: "sequence cost / operations", reason: "Explains occasional expensive operations" }] },
    { type: "common-mistakes", id: "mistakes", title: "Common mistakes", mistakes: [{ mistake: "Counting loops instead of iterations", consequence: "Two nested loops are incorrectly labeled quadratic even when the inner range is bounded.", correction: "Sum the actual executions of the dominant operation." }, { mistake: "Using Big-O as an exact runtime", consequence: "O(n²) is interpreted as proof that an algorithm is always slower than O(n).", correction: "Big-O is an eventual upper bound; constants, input range, and implementation still matter." }, { mistake: "Calling amortized analysis average-case analysis", consequence: "A guarantee over every operation sequence is confused with a probability model.", correction: "State whether randomness comes from inputs, the algorithm, or neither." }] },
    { type: "exercise", id: "ex-loop", title: "Exercise: dependent loop", exerciseType: "calculation", difficulty: "easy", prompt: "A loop runs i from 1 to n and performs floor(n / i) constant-time operations. Give a tight asymptotic bound.", hints: ["Write the total as a summation.", "Compare the sum to the harmonic series."], solution: "The cost is Σᵢ₌₁ⁿ floor(n/i). Removing floors changes the sum by at most n, and nΣ(1/i) = nHₙ. Since Hₙ ∈ Θ(log n), the total is Θ(n log n).", explanation: "The inner workload is not constant and not triangular; it follows a harmonic pattern.", relatedTopicIds: ["complexity-analysis"], estimatedMinutes: 12 },
    { type: "exercise", id: "ex-recursion", title: "Exercise: recursive cost", exerciseType: "calculation", difficulty: "medium", prompt: "Solve T(n) = 2T(n/2) + n with T(1) = Θ(1).", hints: ["Draw the recursion tree.", "Compute the total non-recursive work at each depth."], solution: "Each level performs Θ(n) combine work. There are log₂n + 1 levels, so T(n) ∈ Θ(n log n).", explanation: "The number of subproblems grows while their individual size shrinks; the aggregate work per level stays linear.", relatedTopicIds: ["recursion", "sorting"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-claim", title: "Exercise: challenge a claim", exerciseType: "proof", difficulty: "hard", prompt: "A developer claims that 2ⁿ is O(1.99ⁿ) because the bases are close. Prove or refute the claim.", hints: ["Examine the ratio 2ⁿ/1.99ⁿ.", "Ask whether a fixed constant can bound that ratio for all sufficiently large n."], solution: "The claim is false. The ratio (2/1.99)ⁿ grows without bound, so no constant c can make 2ⁿ ≤ c·1.99ⁿ for all sufficiently large n.", explanation: "Constant factors may be discarded, but changing the base of an exponential changes its asymptotic growth.", relatedTopicIds: ["complexity-analysis"], estimatedMinutes: 18 },
    { type: "further-reading", id: "reading", title: "Further reading", sourceIds: ["clrs-4e"], body: "Use the asymptotic notation and recurrences chapters for formal definitions, then revisit the analysis chapters while tracing concrete algorithms." },
  ],
};

const gradientDescent: DeepTopicProfile = {
  estimatedMinutes: 105,
  sourceIds: ["mml-book"],
  objectives: ["Interpret a gradient as a local direction of steepest increase.", "Derive the gradient-descent update from a first-order approximation.", "Trace optimization on a scalar quadratic objective.", "Explain the effect of learning rate and feature scaling.", "Distinguish batch, stochastic, and mini-batch updates.", "Diagnose divergence, oscillation, and slow convergence."],
  glossary: [{ term: "Gradient", definition: "The vector of partial derivatives; it points in the direction of steepest local increase under the Euclidean norm." }, { term: "Learning rate", definition: "A positive step-size parameter controlling how far an update moves along the negative gradient." }, { term: "Conditioning", definition: "How unevenly an objective curves in different directions; poor conditioning slows first-order optimization." }],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Learning objectives", objectives: ["Derive the update rule", "Compute gradients by hand", "Choose and diagnose a learning rate", "Connect optimization behavior to scaling and curvature"] },
    { type: "intuition", id: "intuition", title: "Follow the local slope", body: "At a differentiable point, the gradient summarizes the local slope in every coordinate. Moving a small distance in the opposite direction decreases the function most rapidly among equally sized Euclidean steps.", analogy: "Imagine standing on a smooth hillside in fog. The gradient is the uphill arrow under your feet; turn around to descend." },
    { type: "formula", id: "update-rule", title: "The update rule", expression: "θₜ₊₁ = θₜ − η∇J(θₜ)", description: "Each iteration evaluates the objective gradient at the current parameters and takes a step in the negative-gradient direction.", terms: [{ symbol: "θₜ", meaning: "Parameter vector at iteration t" }, { symbol: "η", meaning: "Learning rate" }, { symbol: "J", meaning: "Objective or loss function" }, { symbol: "∇J(θₜ)", meaning: "Gradient evaluated at the current parameters" }], citations: [{ sourceId: "mml-book", locator: "Chapter 7" }] },
    { type: "derivation", id: "derivation", title: "Derive the step from local linearization", introduction: "A first-order Taylor approximation predicts how the objective changes for a small displacement Δ.", steps: [{ expression: "J(θ + Δ) ≈ J(θ) + ∇J(θ)ᵀΔ", explanation: "Locally, the objective is approximated by a hyperplane." }, { expression: "minimize ∇J(θ)ᵀΔ subject to ‖Δ‖₂ ≤ η‖∇J(θ)‖₂", explanation: "Choose a bounded step that makes the predicted change as negative as possible." }, { expression: "Δ = −η∇J(θ)", explanation: "By the Cauchy–Schwarz inequality, the most negative inner product occurs opposite the gradient." }], conclusion: "Gradient descent is a local method: the linear approximation justifies the direction, while η determines whether the step remains trustworthy." },
    { type: "worked-example", id: "quadratic-example", title: "Worked example: minimize a scalar quadratic", problem: "Minimize J(θ) = (θ − 3)² starting from θ₀ = 0 with learning rate η = 0.25.", steps: [{ title: "Differentiate", explanation: "The derivative is twice the distance from the minimizer.", formula: "J′(θ) = 2(θ − 3)" }, { title: "First update", explanation: "At θ₀ = 0, the derivative is −6.", formula: "θ₁ = 0 − 0.25(−6) = 1.5" }, { title: "Second update", explanation: "At θ₁ = 1.5, the derivative is −3.", formula: "θ₂ = 1.5 − 0.25(−3) = 2.25" }, { title: "Observe contraction", explanation: "Every step halves the remaining distance to 3.", formula: "3 − θₜ₊₁ = 0.5(3 − θₜ)" }], conclusion: "The sequence 0, 1.5, 2.25, 2.625, … converges geometrically to the minimizer 3." },
    { type: "worked-example", id: "learning-rate-example", title: "Worked example: when the step is too large", problem: "Use the same objective J(θ) = (θ − 3)² but choose η = 1.1.", steps: [{ title: "Write the error update", explanation: "Let eₜ = θₜ − 3. Substitution isolates the convergence behavior.", formula: "eₜ₊₁ = (1 − 2η)eₜ" }, { title: "Substitute η", explanation: "The multiplier is −1.2.", formula: "eₜ₊₁ = −1.2eₜ" }, { title: "Interpret", explanation: "The sign flips on every iteration and the magnitude grows by 20%." }], conclusion: "A direction can be correct while a step size is destructive. Gradient descent diverges here." },
    { type: "comparison", id: "variants", title: "Update variants", columns: ["Gradient estimate", "Strength", "Tradeoff"], rows: [{ label: "Batch", values: ["All training examples", "Stable and deterministic", "Expensive per update"] }, { label: "Stochastic", values: ["One example", "Frequent, noisy updates", "High variance"] }, { label: "Mini-batch", values: ["Small batch", "Hardware-efficient compromise", "Requires batch-size choice"] }] },
    { type: "code", id: "implementation", title: "Reference implementation", language: "python", code: "def gradient_descent(gradient, initial, learning_rate=0.1, steps=100):\n    theta = initial\n    history = [theta]\n    for _ in range(steps):\n        theta = theta - learning_rate * gradient(theta)\n        history.append(theta)\n    return theta, history", explanation: [{ lines: "1", body: "Accept the gradient as a function so the optimizer stays independent of a specific objective." }, { lines: "2–3", body: "Keep the current parameter and a history for convergence diagnostics." }, { lines: "4–6", body: "Apply the state-driven update exactly once per iteration." }, { lines: "7", body: "Return both the final value and trace; optimization should be inspected, not merely run." }] },
    { type: "callout", id: "scaling", title: "Feature scaling changes the geometry", tone: "insight", body: "When one feature spans thousands and another spans fractions, level sets become elongated. A single learning rate then oscillates across the steep direction while crawling along the shallow direction. Standardization often improves conditioning." },
    { type: "common-mistakes", id: "mistakes", title: "Common mistakes", mistakes: [{ mistake: "Treating a decreasing training loss as proof of generalization", consequence: "Optimization success is confused with model quality on unseen data.", correction: "Track validation behavior separately from the optimization objective." }, { mistake: "Using one learning rate without inspecting the trace", consequence: "Slow convergence or divergence goes unnoticed.", correction: "Plot loss and gradient norms; test rates on a logarithmic scale." }, { mistake: "Stopping only after a fixed iteration count", consequence: "Runs may stop far too early or waste computation.", correction: "Also consider objective change, gradient norm, or validation-based stopping." }] },
    { type: "exercise", id: "ex-update", title: "Exercise: two manual updates", exerciseType: "calculation", difficulty: "easy", prompt: "For J(θ) = θ² + 4θ, start at θ₀ = 2 and perform two updates with η = 0.1.", hints: ["Differentiate J first.", "Apply the update using the newly computed θ each time."], solution: "J′(θ)=2θ+4. θ₁=2−0.1(8)=1.2. θ₂=1.2−0.1(6.4)=0.56.", explanation: "The minimizer is −2, so both updates move left toward it.", relatedTopicIds: ["gradient-descent", "optimization"], estimatedMinutes: 8 },
    { type: "exercise", id: "ex-rate", title: "Exercise: convergence interval", exerciseType: "proof", difficulty: "medium", prompt: "For J(θ)=aθ²/2 with a>0, derive the range of constant learning rates that makes gradient descent converge.", hints: ["Write θₜ₊₁ as a multiple of θₜ.", "Convergence requires the multiplier magnitude to be below one."], solution: "The gradient is aθ, so θₜ₊₁=(1−ηa)θₜ. Convergence requires |1−ηa|<1, which gives 0<η<2/a.", explanation: "Curvature a sets the largest stable step size.", relatedTopicIds: ["gradient-descent", "optimization"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-debug", title: "Exercise: debug an optimizer", exerciseType: "debugging", difficulty: "hard", prompt: "Training loss becomes NaN after several steps. Give a prioritized diagnostic plan rather than listing unrelated possibilities.", hints: ["Start with the update magnitude.", "Inspect data and arithmetic only after reproducing the first non-finite value."], solution: "Reproduce the first failing step; log loss, gradient norm, parameter norm, and batch. Reduce the learning rate; check unscaled inputs and exploding gradients; verify the loss domain such as log(0); then add numerically stable operations or clipping only when the trace supports them.", explanation: "A temporal trace narrows the fault more effectively than speculative fixes.", relatedTopicIds: ["gradient-descent", "deep-optimization"], estimatedMinutes: 20 },
    { type: "further-reading", id: "reading", title: "Further reading", sourceIds: ["mml-book"], body: "Study continuous optimization after vector calculus, then connect the update geometry to linear regression and neural-network training." },
  ],
};

const linearRegression: DeepTopicProfile = {
  estimatedMinutes: 120,
  sourceIds: ["mml-book", "isl", "sklearn-guide"],
  objectives: ["Formulate linear regression in scalar and matrix notation.", "Derive ordinary least squares from the squared-error objective.", "Interpret coefficients conditionally rather than causally.", "Fit a model with gradient descent and the normal equations.", "Diagnose residual structure, multicollinearity, and data leakage.", "Select suitable error metrics and establish a baseline."],
  glossary: [{ term: "Residual", definition: "The observed target minus its fitted value: eᵢ = yᵢ − ŷᵢ." }, { term: "Design matrix", definition: "The matrix whose rows are observations and columns are input features, often augmented with an intercept column." }, { term: "Ordinary least squares", definition: "The parameter estimate that minimizes the sum of squared residuals." }],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Learning objectives", objectives: ["Translate a prediction problem into matrix form", "Derive and implement least squares", "Read coefficients with their assumptions", "Evaluate residuals and generalization"] },
    { type: "intuition", id: "intuition", title: "A global linear approximation", body: "Linear regression chooses the affine surface whose predictions are collectively closest to the observed targets under squared error. The model is simple, but the workflow around it—feature definition, leakage control, residual diagnosis, and uncertainty—is not.", analogy: "In one dimension, imagine balancing vertical squared distances around a line; large misses pull more strongly because they are squared." },
    { type: "formula", id: "model", title: "Model and objective", expression: "ŷ = Xw + b1,   J(w,b) = (1/n)‖y − ŷ‖²₂", description: "The prediction is linear in its parameters. Squared loss measures average vertical discrepancy and yields a differentiable convex objective.", terms: [{ symbol: "X ∈ ℝⁿˣᵈ", meaning: "Design matrix with n observations and d features" }, { symbol: "w ∈ ℝᵈ", meaning: "Feature coefficients" }, { symbol: "b", meaning: "Intercept" }, { symbol: "y", meaning: "Observed targets" }], citations: [{ sourceId: "mml-book", locator: "Chapter 9" }, { sourceId: "isl", locator: "Linear Regression" }] },
    { type: "worked-example", id: "fit-line", title: "Worked example: fit a line by hand", problem: "Fit y = wx + b to the points (1,2), (2,3), and (3,5).", steps: [{ title: "Compute means", explanation: "The line passes through the sample means.", formula: "x̄=2, ȳ=10/3" }, { title: "Compute the slope", explanation: "Divide centered cross-products by centered x squares.", formula: "w = Σ(xᵢ−x̄)(yᵢ−ȳ) / Σ(xᵢ−x̄)² = 3/2" }, { title: "Compute the intercept", explanation: "Use b = ȳ − wx̄.", formula: "b = 10/3 − 3 = 1/3" }, { title: "Inspect residuals", explanation: "Predictions are 11/6, 10/3, and 29/6; residuals sum to zero when an intercept is fitted." }], conclusion: "The fitted line is ŷ = 1.5x + 0.333. A small dataset makes every assumption visible." },
    { type: "derivation", id: "normal-equation", title: "Derive the normal equation", introduction: "Absorb the intercept into X by adding a column of ones and minimize the unscaled squared norm.", steps: [{ expression: "J(w) = (y − Xw)ᵀ(y − Xw)", explanation: "Write squared error as an inner product." }, { expression: "∇J(w) = −2Xᵀ(y − Xw)", explanation: "Differentiate the quadratic with respect to w." }, { expression: "XᵀXw = Xᵀy", explanation: "Set the gradient to zero at a stationary point." }, { expression: "ŵ = (XᵀX)⁻¹Xᵀy", explanation: "This form requires XᵀX to be invertible; practical solvers prefer QR or SVD over forming the inverse." }], conclusion: "The objective is convex, so any solution of the normal equations is globally optimal. Rank deficiency may make the minimizer non-unique." },
    { type: "code", id: "implementation", title: "NumPy implementation with stable least squares", language: "python", code: "import numpy as np\n\ndef fit_linear_regression(X, y):\n    X = np.asarray(X, dtype=float)\n    y = np.asarray(y, dtype=float)\n    design = np.column_stack([np.ones(len(X)), X])\n    coefficients, *_ = np.linalg.lstsq(design, y, rcond=None)\n    return coefficients[0], coefficients[1:]\n\ndef predict(X, intercept, weights):\n    return np.asarray(X, dtype=float) @ weights + intercept", explanation: [{ lines: "4–5", body: "Normalize input types and expose shape errors early." }, { lines: "6", body: "Add an intercept column explicitly." }, { lines: "7", body: "Use a least-squares solver based on stable matrix factorization instead of inverting XᵀX." }, { lines: "10–11", body: "Keep prediction separate from fitting so evaluation can use untouched data." }], citations: [{ sourceId: "mml-book", locator: "Chapter 9" }] },
    { type: "comparison", id: "solvers", title: "Closed form versus gradient methods", columns: ["Best fit", "Strength", "Limitation"], rows: [{ label: "QR/SVD least squares", values: ["Small or medium dense problems", "Stable and no learning rate", "Factorization cost grows with feature count"] }, { label: "Batch gradient descent", values: ["Large differentiable objectives", "Simple and extensible", "Sensitive to scaling and step size"] }, { label: "Stochastic optimization", values: ["Very large or streaming data", "Cheap frequent updates", "Noisy convergence"] }] },
    { type: "callout", id: "interpretation", title: "Prediction is not causation", tone: "warning", body: "A coefficient describes a conditional association inside the fitted feature set. Confounding, selection bias, measurement error, and interventions require additional causal assumptions that least squares does not provide." },
    { type: "step-by-step", id: "workflow", title: "A leakage-safe workflow", steps: [{ title: "Define the prediction unit", body: "State what one row represents and what information is available at prediction time." }, { title: "Reserve evaluation data", body: "Split before fitting scalers, imputers, encoders, or feature selection." }, { title: "Build a baseline", body: "Compare against predicting the training mean or another domain-appropriate naive rule." }, { title: "Fit a pipeline", body: "Estimate preprocessing parameters on training folds only." }, { title: "Inspect residuals", body: "Look for curvature, changing variance, grouped errors, influential observations, and temporal structure." }, { title: "Report uncertainty", body: "Include variation across folds or intervals when the decision requires it." }] },
    { type: "complexity", id: "complexity", title: "Computational cost", time: "Solver-dependent; dense least squares is commonly O(nd² + d³)", space: "O(nd) to materialize the design matrix", analysis: "When n is much larger than d, accumulating cross-products or using iterative solvers may reduce memory. Sparsity changes both storage and solver choices.", cases: [{ name: "Prediction", complexity: "O(nd)", reason: "One dot product per observation" }, { name: "One gradient step", complexity: "O(nd)", reason: "Compute predictions and Xᵀ residuals" }] },
    { type: "common-mistakes", id: "mistakes", title: "Common mistakes", mistakes: [{ mistake: "Fitting preprocessing before the split", consequence: "Validation data influences the training representation and performance looks optimistic.", correction: "Fit every learned transformation inside a training-only pipeline." }, { mistake: "Reading a large coefficient as feature importance", consequence: "Units, correlation, and encoding distort coefficient magnitude.", correction: "Interpret coefficients in context and use standardized or domain-meaningful units." }, { mistake: "Judging the model only by R²", consequence: "Systematic residual errors or unacceptable absolute error remain hidden.", correction: "Use decision-relevant metrics and residual diagnostics." }] },
    { type: "exercise", id: "ex-predict", title: "Exercise: predictions and residuals", exerciseType: "calculation", difficulty: "easy", prompt: "For ŷ = 2x − 1 and observations (1,2), (2,2), (4,8), compute predictions, residuals, and MSE.", hints: ["Residual means observed minus predicted.", "Square each residual before averaging."], solution: "Predictions are 1, 3, 7. Residuals are 1, −1, 1. MSE=(1+1+1)/3=1.", explanation: "Residual signs show direction; MSE discards sign and penalizes magnitude.", relatedTopicIds: ["linear-regression", "regression-losses"], estimatedMinutes: 8 },
    { type: "exercise", id: "ex-leakage", title: "Exercise: find the leakage", exerciseType: "debugging", difficulty: "medium", prompt: "A team standardizes the complete dataset, selects features using every target, and then performs cross-validation. Identify each leakage path and redesign the procedure.", hints: ["Ask which operations learned from held-out rows.", "Put learned transformations inside each fold."], solution: "Both scaling statistics and target-informed feature selection use validation folds. Split first and fit scaling plus selection within a pipeline separately in every training fold; reserve a final untouched test set for one final estimate.", explanation: "Cross-validation is valid only when every learned operation is repeated within its training partition.", relatedTopicIds: ["linear-regression", "model-evaluation", "feature-processing"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-rank", title: "Exercise: rank deficiency", exerciseType: "conceptual", difficulty: "hard", prompt: "A design matrix contains age in years, age in months, and an intercept. Explain the numerical and interpretive problem.", hints: ["One column is an exact multiple of another.", "Consider whether XᵀX is invertible."], solution: "Age in months equals 12 times age in years, so the feature columns are linearly dependent. X lacks full column rank, XᵀX is singular, and infinitely many coefficient pairs produce identical predictions. Remove one redundant feature or use a regularized formulation while interpreting coefficients carefully.", explanation: "Prediction may remain possible even when individual coefficients are not identifiable.", relatedTopicIds: ["linear-regression", "linear-algebra"], estimatedMinutes: 18 },
    { type: "applications", id: "applications", title: "Where linear regression is useful", applications: [{ name: "Interpretable baseline", description: "Establish whether nonlinear models add value beyond a transparent additive relation." }, { name: "Calibration and trend estimation", description: "Estimate systematic linear relationships when assumptions are defensible." }, { name: "Local components", description: "Use linear models inside larger pipelines, residual corrections, and generalized linear frameworks." }] },
    { type: "further-reading", id: "reading", title: "Further reading", sourceIds: ["mml-book", "isl", "sklearn-guide"], body: "Read a mathematical derivation, a statistical-learning treatment, and the implementation guide together; each answers a different part of the modeling problem." },
  ],
};

export const deepTopicProfiles: Record<string, DeepTopicProfile> = {
  "complexity-analysis": complexity,
  "gradient-descent": gradientDescent,
  "linear-regression": linearRegression,
};
