import type { Project } from "@/lib/types";

export const projects: Project[] = [
  { id: "cli-study-tracker", slug: "cli-study-tracker", title: "CLI Study Tracker", domainId: "programming", summary: "Build a typed command-line tool with file persistence, validation, and tests.", difficulty: "Foundational", deliverables: ["Command parser", "JSON storage adapter", "Test suite"], skillIds: ["python", "modules", "debugging"] },
  { id: "route-planner", slug: "route-planner", title: "Graph Route Planner", domainId: "data-structures-algorithms", summary: "Model a transit network and compare BFS with Dijkstra under different edge costs.", difficulty: "Intermediate", deliverables: ["Adjacency-list graph", "Path reconstruction", "Complexity analysis"], skillIds: ["graphs", "shortest-paths"] },
  { id: "algorithm-lab", slug: "algorithm-lab", title: "Algorithm Experiment Lab", domainId: "data-structures-algorithms", summary: "Instrument sorting and searching algorithms to compare theoretical and measured behavior.", difficulty: "Intermediate", deliverables: ["Operation counters", "Benchmark dataset generator", "Results report"], skillIds: ["sorting", "searching", "complexity-analysis"] },
  { id: "gradient-notebook", slug: "gradient-notebook", title: "Gradient Descent from First Principles", domainId: "mathematics-ai", summary: "Derive and implement gradient descent for several convex objectives, then study learning-rate behavior.", difficulty: "Intermediate", deliverables: ["Symbolic derivations", "NumPy implementation", "Convergence plots"], skillIds: ["gradient-descent", "multivariable-calculus"] },
  { id: "data-quality-audit", slug: "data-quality-audit", title: "Reproducible Data Quality Audit", domainId: "data-science", summary: "Turn a messy public dataset into a documented, validated analysis table.", difficulty: "Intermediate", deliverables: ["Cleaning pipeline", "Quality checks", "EDA brief"], skillIds: ["pandas", "data-cleaning", "exploratory-data-analysis"] },
  { id: "model-selection-workbench", slug: "model-selection-workbench", title: "Model Selection Workbench", domainId: "machine-learning", summary: "Compare linear, tree, and ensemble models using leakage-safe pipelines and explicit metrics.", difficulty: "Intermediate", deliverables: ["Baseline pipeline", "Cross-validation study", "Error analysis"], skillIds: ["model-evaluation", "decision-trees", "ensemble-learning"] },
  { id: "tiny-autodiff", slug: "tiny-autodiff", title: "Tiny Autodiff Engine", domainId: "deep-learning", summary: "Implement scalar reverse-mode automatic differentiation and train a tiny neural network.", difficulty: "Advanced", deliverables: ["Computation graph", "Backward pass", "Gradient checks"], skillIds: ["backpropagation", "neural-networks"] },
  { id: "image-segmenter", slug: "image-segmenter", title: "Small Image Segmenter", domainId: "computer-vision", summary: "Train and evaluate a compact segmentation model with visible failure analysis.", difficulty: "Advanced", deliverables: ["Dataset pipeline", "Segmentation model", "Per-class metrics"], skillIds: ["image-segmentation", "convolutional-networks"] },
  { id: "text-classifier", slug: "text-classifier", title: "Text Classification Pipeline", domainId: "nlp", summary: "Compare sparse and embedding-based representations on a labeled text task.", difficulty: "Intermediate", deliverables: ["Preprocessing pipeline", "Two model families", "Confusion analysis"], skillIds: ["text-preprocessing", "word-embeddings"] },
  { id: "grounded-assistant", slug: "grounded-assistant", title: "Grounded Documentation Assistant", domainId: "llm-engineering", summary: "Build a retrieval pipeline that answers from a controlled corpus and exposes its evidence.", difficulty: "Advanced", deliverables: ["Chunking and index pipeline", "Cited answer flow", "Evaluation set"], skillIds: ["rag", "vector-search", "llm-evaluation"] },
  { id: "inference-service", slug: "inference-service", title: "Observable Inference Service", domainId: "ai-engineering", summary: "Serve a model behind a resilient API with tracing, evaluation hooks, and rollout controls.", difficulty: "Advanced", deliverables: ["Typed API", "Latency and quality traces", "Safe rollout plan"], skillIds: ["model-serving", "ai-observability", "ai-deployment"] },
];
