import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { algorithmById, techniqueBySlug, techniques, topicById } from "@/content";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { BookmarkButton, StatusSelect } from "@/components/content-actions";
import { Message } from "@/components/locale-provider";
import { LibraryResources } from "@/components/library/library-resources";
import { RelatedPractice } from "@/components/practice/related-practice";
export function generateStaticParams(){return techniques.map((item)=>({technique:item.slug}))}
export default async function TechniquePage({params}:{params:Promise<{technique:string}>}){const {technique}=await params;const item=techniqueBySlug.get(technique);if(!item)notFound();return <div className="page narrow"><Breadcrumbs items={[{label:"Techniques",href:"/techniques"},{label:item.family},{label:item.name}]}/><header className="page-header"><div><p className="kicker">{item.family} · <Message k="navigation.techniques" /></p><h1>{item.name}</h1><p className="lede" lang="en">{item.summary}</p></div><div className="header-actions"><StatusSelect id={`technique:${item.id}`}/><BookmarkButton bookmark={{id:item.id,type:"technique",title:item.name,href:`/techniques/${item.slug}`,context:item.family}}/></div></header><div className="content-grid" lang="en"><div className="stack"><section className="panel"><h2><Message k="common.whenToUse" /></h2><ul className="list-clean">{item.whenToUse.map((value)=><li key={value}><CheckCircle2 size={15}/>{value}</li>)}</ul></section><section className="panel"><h2><Message k="common.workingMethod" /></h2><ol>{item.steps.map((value,index)=><li key={value} style={{margin:"10px 0",color:"var(--muted)"}}><strong style={{color:"var(--accent)",fontFamily:"var(--font-mono)"}}>{String(index+1).padStart(2,"0")}</strong> &nbsp;{value}</li>)}</ol></section><RelatedPractice entityType="technique" entityId={item.id} /><LibraryResources entityType="technique" entityId={item.id} /></div><aside className="stack"><section className="panel"><h3><Message k="common.connectedTopics" /></h3><ul className="list-clean">{item.topicIds.map((id)=>{const topic=topicById.get(id);return topic?<li key={id}><ArrowRight size={14}/><Link href={`/topics/${topic.slug}`}>{topic.title}</Link></li>:null})}</ul></section>{item.algorithmIds.length>0&&<section className="panel"><h3><Message k="common.algorithmsUsing" /></h3><ul className="list-clean">{item.algorithmIds.map((id)=>{const algorithm=algorithmById.get(id);return algorithm?<li key={id}><ArrowRight size={14}/><Link href={`/algorithms/${algorithm.slug}`}>{algorithm.name}</Link></li>:null})}</ul></section>}</aside></div></div>}
