import type { LocalizedText, PracticeProblem, PracticeTest, JsonValue } from "@/lib/practice/types";
const l = (en: string, vi: string): LocalizedText => ({ en, vi });
const test = (id: string, input: JsonValue, expected: JsonValue, label: LocalizedText, explanation: LocalizedText): PracticeTest => ({ id, input, expected, label, explanation });
const dsa = "data-structures-algorithms";

export const practiceProblems: PracticeProblem[] = [
  {
    id: "first-occurrence", version: 1, kind: "dsa", difficulty: "easy", domainId: dsa,
    title: l("First occurrence", "Vị trí xuất hiện đầu tiên"), summary: l("Find the leftmost target in a sorted array, including duplicates.", "Tìm vị trí đầu tiên của mục tiêu trong mảng đã sắp xếp, kể cả khi có phần tử trùng."),
    topicIds: ["searching", "arrays", "complexity-analysis"], algorithmIds: ["binary-search"], techniqueIds: ["binary-search-on-answer"],
    statement: l("Given a nondecreasing integer array nums and an integer target, return the smallest zero-based index whose value equals target. Return -1 if it does not exist. Aim for logarithmic time; passing small public tests alone does not prove that complexity.", "Cho mảng số nguyên nums không giảm và số nguyên target. Trả về chỉ số nhỏ nhất (bắt đầu từ 0) có giá trị bằng target; trả -1 nếu không tồn tại. Hướng tới thời gian logarit; vượt qua test công khai nhỏ chưa chứng minh được độ phức tạp."),
    contract: l("solve({ nums, target }) → integer index or -1. Do not print; return the answer.", "solve({ nums, target }) → chỉ số nguyên hoặc -1. Trả về đáp án, không in ra."),
    constraints: [l("0 ≤ nums.length ≤ 100,000; values and target are integers in [-10⁹, 10⁹].", "0 ≤ nums.length ≤ 100.000; các giá trị và target là số nguyên trong [-10⁹, 10⁹].")],
    starters: {
      python: "def solve(data):\n    nums, target = data[\"nums\"], data[\"target\"]\n    # Return the first matching index, or -1.\n    return -1",
      javascript: "function solve({ nums, target }) {\n  // Return the first matching index, or -1.\n  return -1;\n}",
    }, comparator: "exact",
    tests: [
      test("duplicates", { nums: [1, 2, 2, 2, 5], target: 2 }, 1, l("Repeated target", "Mục tiêu bị trùng"), l("The first 2 is at index 1, not 2 or 3.", "Số 2 đầu tiên nằm ở chỉ số 1, không phải 2 hay 3.")),
      test("empty", { nums: [], target: 7 }, -1, l("Empty array", "Mảng rỗng"), l("There is no valid index.", "Không có chỉ số hợp lệ.")),
      test("missing", { nums: [-4, 0, 9], target: 2 }, -1, l("Absent between values", "Không có giữa hai giá trị"), l("The insertion point is not a match.", "Vị trí chèn không phải vị trí khớp.")),
      test("single", { nums: [8], target: 8 }, 0, l("Single element", "Một phần tử"), l("Index zero is a valid result.", "Chỉ số 0 là kết quả hợp lệ.")),
      test("left", { nums: [-3, -3, 2], target: -3 }, 0, l("Left boundary", "Biên trái"), l("Repeated values may start at zero.", "Giá trị trùng có thể bắt đầu tại 0.")),
      test("right", { nums: [1, 4, 8], target: 10 }, -1, l("Beyond the end", "Ngoài biên phải"), l("The lower bound can equal the array length.", "Cận dưới có thể bằng độ dài mảng.")),
    ],
    hints: [l("A match may have an earlier equal value.", "Một vị trí khớp có thể còn giá trị bằng nó ở phía trước."), l("Search for the first index where nums[index] ≥ target.", "Tìm chỉ số đầu tiên có nums[index] ≥ target."), l("Maintain [lo, hi), initially [0, n). Move hi to mid on ≥ target; otherwise move lo to mid + 1. Finally check equality.", "Duy trì [lo, hi), ban đầu [0, n). Nếu ≥ target thì hi = mid; ngược lại lo = mid + 1. Cuối cùng kiểm tra bằng nhau.")],
    complexity: l("Target: O(log n) time, O(1) extra space. Explain why the interval shrinks on every iteration.", "Mục tiêu: O(log n) thời gian, O(1) bộ nhớ phụ. Giải thích vì sao khoảng tìm kiếm luôn thu nhỏ."),
  },
  {
    id: "unweighted-distance", version: 1, kind: "dsa", difficulty: "medium", domainId: dsa,
    title: l("Shortest unweighted path", "Đường đi ngắn nhất không trọng số"), summary: l("Use BFS to measure distance in a graph with cycles and disconnected vertices.", "Dùng BFS tính khoảng cách trong đồ thị có chu trình và đỉnh không liên thông."),
    topicIds: ["graph-traversal", "graphs", "stacks-queues"], algorithmIds: ["bfs"], techniqueIds: [],
    statement: l("adj is an adjacency list for a directed, unweighted graph with vertices 0…n−1. Return the minimum number of edges from start to goal, or -1 if unreachable. Mark vertices when enqueuing to avoid duplicate work.", "adj là danh sách kề của đồ thị có hướng, không trọng số, các đỉnh 0…n−1. Trả số cạnh ít nhất từ start đến goal, hoặc -1 nếu không tới được. Đánh dấu đỉnh khi đưa vào hàng đợi để tránh lặp."),
    contract: l("solve({ adj, start, goal }) → integer distance. A vertex has distance 0 from itself.", "solve({ adj, start, goal }) → khoảng cách nguyên. Khoảng cách từ một đỉnh tới chính nó là 0."),
    constraints: [l("1 ≤ n ≤ 10,000; ≤ 50,000 edges; start, goal and all neighbors are valid vertex indices.", "1 ≤ n ≤ 10.000; ≤ 50.000 cạnh; start, goal và các đỉnh kề đều là chỉ số hợp lệ.")],
    starters: {
      python: "def solve(data):\n    adj = data[\"adj\"]\n    start, goal = data[\"start\"], data[\"goal\"]\n    return -1",
      javascript: "function solve({ adj, start, goal }) {\n  return -1;\n}",
    }, comparator: "exact",
    tests: [
      test("branch", { adj: [[1, 2], [3], [3], []], start: 0, goal: 3 }, 2, l("Two routes", "Hai đường đi"), l("Both 0→1→3 and 0→2→3 have two edges.", "Cả 0→1→3 và 0→2→3 đều có hai cạnh.")),
      test("cycle", { adj: [[1], [0, 2], [1]], start: 0, goal: 2 }, 2, l("Cycle", "Chu trình"), l("Revisiting vertices must not cause an infinite loop.", "Không để việc thăm lại đỉnh gây vòng lặp vô hạn.")),
      test("unreachable", { adj: [[1], [], []], start: 0, goal: 2 }, -1, l("Disconnected", "Không liên thông"), l("Vertex 2 cannot be reached from 0.", "Không thể đi từ 0 tới đỉnh 2.")),
      test("same", { adj: [[]], start: 0, goal: 0 }, 0, l("Same vertex", "Cùng một đỉnh"), l("No edge is needed.", "Không cần đi qua cạnh nào.")),
      test("directed", { adj: [[1], []], start: 1, goal: 0 }, -1, l("Edge direction", "Hướng của cạnh"), l("An edge from 0 to 1 does not imply its reverse.", "Cạnh từ 0 tới 1 không có nghĩa là có cạnh ngược lại.")),
    ],
    hints: [l("Explore vertices in increasing distance from start.", "Khám phá đỉnh theo khoảng cách tăng dần từ start."), l("Store distances initialized to -1, and use a FIFO queue.", "Lưu khoảng cách ban đầu bằng -1 và dùng hàng đợi FIFO."), l("Set dist[start] = 0. Advance a head index through an array queue; assign each unseen neighbor dist[v] + 1 before enqueuing it.", "Đặt dist[start] = 0. Dùng chỉ số đầu hàng đợi mảng; gán cho đỉnh chưa thăm dist[v] + 1 trước khi thêm vào.")],
    complexity: l("Target: O(V + E) time and O(V) extra space. An array with a head index avoids repeated shift() copies.", "Mục tiêu: O(V + E) thời gian, O(V) bộ nhớ phụ. Mảng có chỉ số đầu tránh sao chép lặp do shift()."),
  },
  {
    id: "sorted-pair", version: 1, kind: "dsa", difficulty: "easy", domainId: dsa,
    title: l("Pair sum in a sorted array", "Tổng cặp trong mảng đã sắp xếp"), summary: l("Decide whether two distinct positions sum to a target.", "Kiểm tra hai vị trí khác nhau có tổng bằng mục tiêu hay không."),
    topicIds: ["arrays", "searching"], algorithmIds: ["two-pointers"], techniqueIds: ["two-pointers"],
    statement: l("Given nondecreasing nums, return true if two different indices have values summing to target; otherwise return false. Equal values at different indices are allowed. An element cannot be used twice.", "Cho nums không giảm, trả true nếu có hai chỉ số khác nhau có tổng giá trị bằng target; ngược lại trả false. Hai giá trị bằng nhau ở hai chỉ số khác nhau được phép; không dùng một phần tử hai lần."),
    contract: l("solve({ nums, target }) → boolean, not indices or strings.", "solve({ nums, target }) → boolean, không phải chỉ số hoặc chuỗi."),
    constraints: [l("0 ≤ n ≤ 100,000; integer values in [-10⁶, 10⁶].", "0 ≤ n ≤ 100.000; giá trị nguyên trong [-10⁶, 10⁶].")],
    starters: {
      python: "def solve(data):\n    nums, target = data[\"nums\"], data[\"target\"]\n    return False",
      javascript: "function solve({ nums, target }) {\n  return false;\n}",
    }, comparator: "exact",
    tests: [
      test("found", { nums: [1, 2, 4, 7], target: 6 }, true, l("Pair exists", "Có cặp"), l("2 + 4 = 6.", "2 + 4 = 6.")),
      test("single", { nums: [3], target: 6 }, false, l("Do not reuse", "Không dùng lại"), l("Only one index exists.", "Chỉ có một chỉ số.")),
      test("equal", { nums: [3, 3], target: 6 }, true, l("Equal values", "Giá trị bằng nhau"), l("The two 3s occupy different indices.", "Hai số 3 ở hai vị trí khác nhau.")),
      test("negative", { nums: [-5, -1, 0, 4], target: -1 }, true, l("Negative values", "Giá trị âm"), l("-5 + 4 = -1.", "-5 + 4 = -1.")),
      test("empty", { nums: [], target: 0 }, false, l("Empty", "Rỗng"), l("No pair exists.", "Không có cặp nào.")),
      test("missing", { nums: [1, 2, 8], target: 7 }, false, l("No solution", "Không có lời giải"), l("Every pair has a different total.", "Mọi cặp đều có tổng khác mục tiêu.")),
    ],
    hints: [l("The sorted order tells you which direction changes the sum.", "Thứ tự đã sắp xếp cho biết hướng nào làm tổng tăng hay giảm."), l("Start with the leftmost and rightmost values.", "Bắt đầu với phần tử ngoài cùng bên trái và bên phải."), l("While left < right, increase left if the sum is too small; decrease right if it is too large. Return true on equality.", "Khi left < right, tăng left nếu tổng quá nhỏ; giảm right nếu quá lớn. Trả true khi bằng nhau.")],
    complexity: l("Target: O(n) time, O(1) extra space. Each pointer moves at most n times.", "Mục tiêu: O(n) thời gian, O(1) bộ nhớ phụ. Mỗi con trỏ di chuyển tối đa n lần."),
  },
  {
    id: "unique-window", version: 1, kind: "dsa", difficulty: "medium", domainId: dsa,
    title: l("Longest distinct substring", "Chuỗi con dài nhất không lặp"), summary: l("Maintain a valid sliding window without moving its left edge backwards.", "Duy trì cửa sổ hợp lệ mà không lùi biên trái."),
    topicIds: ["strings", "hash-tables", "arrays"], algorithmIds: ["sliding-window"], techniqueIds: ["sliding-window"],
    statement: l("Return the length of the longest contiguous substring of s containing no repeated characters. Inputs are restricted to lowercase ASCII letters, so JavaScript code-unit indexing is sufficient.", "Trả độ dài chuỗi con liên tiếp dài nhất của s không có ký tự lặp. Đầu vào chỉ gồm chữ cái ASCII thường, nên chỉ số code unit của JavaScript là đủ."),
    contract: l("solve({ s }) → nonnegative integer length.", "solve({ s }) → độ dài nguyên không âm."),
    constraints: [l("0 ≤ s.length ≤ 100,000; only a–z.", "0 ≤ s.length ≤ 100.000; chỉ gồm a–z.")],
    starters: {
      python: "def solve(data):\n    s = data[\"s\"]\n    return 0",
      javascript: "function solve({ s }) {\n  return 0;\n}",
    }, comparator: "exact",
    tests: [
      test("repeated", { s: "abcabcbb" }, 3, l("Repeated pattern", "Mẫu lặp"), l("abc is a valid window of length 3.", "abc là cửa sổ hợp lệ dài 3.")),
      test("backtrack", { s: "abba" }, 2, l("Old occurrence", "Vị trí xuất hiện cũ"), l("The final a must not move the left edge backwards.", "Chữ a cuối không được làm biên trái lùi lại.")),
      test("empty", { s: "" }, 0, l("Empty string", "Chuỗi rỗng"), l("The answer is zero.", "Đáp án bằng 0.")),
      test("same", { s: "aaaa" }, 1, l("All identical", "Tất cả giống nhau"), l("Only one character fits in a valid window.", "Cửa sổ hợp lệ chỉ chứa được một ký tự.")),
      test("end", { s: "dvdf" }, 3, l("Best at the end", "Tốt nhất ở cuối"), l("vdf has length 3.", "vdf có độ dài 3.")),
    ],
    hints: [l("Keep only windows with unique characters.", "Chỉ giữ cửa sổ có ký tự duy nhất."), l("Remember each character's last position.", "Ghi nhớ vị trí xuất hiện cuối của từng ký tự."), l("For index right and character c, set left = max(left, last[c] + 1), update last[c], then maximize right − left + 1.", "Tại right với ký tự c, đặt left = max(left, last[c] + 1), cập nhật last[c], rồi tối đa hóa right − left + 1.")],
    complexity: l("Target: O(n) time, O(1) auxiliary space for the fixed 26-letter alphabet.", "Mục tiêu: O(n) thời gian, O(1) bộ nhớ phụ với bảng chữ cái cố định 26 ký tự."),
  },
  {
    id: "range-totals", version: 1, kind: "dsa", difficulty: "easy", domainId: dsa,
    title: l("Inclusive range totals", "Tổng trên đoạn đóng"), summary: l("Answer many range-sum queries with a leading-zero prefix array.", "Trả lời nhiều truy vấn tổng đoạn bằng mảng tiền tố có số 0 đầu."),
    topicIds: ["arrays", "complexity-analysis"], algorithmIds: ["prefix-sum"], techniqueIds: ["prefix-sum"],
    statement: l("For each query [left, right], return the sum of nums[left…right], including both endpoints. Keep the query order. The array never changes.", "Với mỗi truy vấn [left, right], trả tổng nums[left…right], gồm cả hai đầu. Giữ thứ tự truy vấn. Mảng không thay đổi."),
    contract: l("solve({ nums, queries }) → array of integer totals.", "solve({ nums, queries }) → mảng tổng nguyên."),
    constraints: [l("1 ≤ n ≤ 100,000; 0 ≤ queries.length ≤ 100,000; −10⁶ ≤ values ≤ 10⁶; 0 ≤ left ≤ right < n.", "1 ≤ n ≤ 100.000; 0 ≤ số truy vấn ≤ 100.000; −10⁶ ≤ giá trị ≤ 10⁶; 0 ≤ left ≤ right < n.")],
    starters: {
      python: "def solve(data):\n    nums, queries = data[\"nums\"], data[\"queries\"]\n    return []",
      javascript: "function solve({ nums, queries }) {\n  return [];\n}",
    }, comparator: "exact",
    tests: [
      test("mixed", { nums: [2, -1, 4, 3], queries: [[0, 3], [1, 2], [2, 2]] }, [8, 3, 4], l("Mixed ranges", "Nhiều dạng đoạn"), l("The totals are 8, -1+4=3, and 4.", "Các tổng là 8, -1+4=3, và 4.")),
      test("single", { nums: [-5], queries: [[0, 0]] }, [-5], l("Single negative", "Một số âm"), l("Do not clamp negative totals to zero.", "Không ép tổng âm về 0.")),
      test("none", { nums: [7], queries: [] }, [], l("No queries", "Không có truy vấn"), l("An empty answer array is valid.", "Mảng đáp án rỗng là hợp lệ.")),
      test("zeros", { nums: [0, 0, 0], queries: [[0, 2], [1, 1]] }, [0, 0], l("Zeros", "Các số 0"), l("Both queries sum to zero.", "Cả hai truy vấn có tổng bằng 0.")),
    ],
    hints: [l("Adjacent range sums share most of their work.", "Các tổng đoạn dùng chung phần lớn phép tính."), l("Let prefix[i] sum the first i elements, with prefix[0] = 0.", "Đặt prefix[i] là tổng i phần tử đầu, prefix[0] = 0."), l("Build prefix[i+1] = prefix[i] + nums[i]. Answer [l,r] using prefix[r+1] − prefix[l].", "Tạo prefix[i+1] = prefix[i] + nums[i]. Trả [l,r] bằng prefix[r+1] − prefix[l].")],
    complexity: l("Target: O(n + q) time, O(n) auxiliary space plus O(q) output.", "Mục tiêu: O(n + q) thời gian, O(n) bộ nhớ phụ và O(q) đầu ra."),
  },
  {
    id: "budget-knapsack", version: 1, kind: "dsa", difficulty: "medium", domainId: dsa,
    title: l("Pick once: 0/1 knapsack", "Chọn một lần: ba lô 0/1"), summary: l("Maximize value within capacity while using each item at most once.", "Tối đa giá trị trong sức chứa, mỗi món chỉ dùng tối đa một lần."),
    topicIds: ["dynamic-programming", "arrays"], algorithmIds: ["knapsack-01"], techniqueIds: ["tabulation", "memoization"],
    statement: l("Each item is [weight, value]. Choose a subset whose total weight is at most capacity and return the maximum total value. Items are indivisible and can be selected only once; selecting none is allowed.", "Mỗi món là [weight, value]. Chọn tập con có tổng trọng lượng không vượt capacity và trả tổng giá trị lớn nhất. Không chia nhỏ hay chọn lặp một món; được phép không chọn gì."),
    contract: l("solve({ items, capacity }) → maximum integer value.", "solve({ items, capacity }) → giá trị nguyên lớn nhất."),
    constraints: [l("0 ≤ items.length ≤ 100; 0 ≤ capacity ≤ 1,000; 1 ≤ weight ≤ 1,000; 0 ≤ value ≤ 10,000.", "0 ≤ số món ≤ 100; 0 ≤ capacity ≤ 1.000; 1 ≤ weight ≤ 1.000; 0 ≤ value ≤ 10.000.")],
    starters: {
      python: "def solve(data):\n    items, capacity = data[\"items\"], data[\"capacity\"]\n    return 0",
      javascript: "function solve({ items, capacity }) {\n  return 0;\n}",
    }, comparator: "exact",
    tests: [
      test("combine", { items: [[2, 3], [3, 4], [4, 5]], capacity: 5 }, 7, l("Combination", "Kết hợp"), l("Pick weights 2 and 3 for value 7.", "Chọn trọng lượng 2 và 3, giá trị 7.")),
      test("once", { items: [[2, 3]], capacity: 4 }, 3, l("No repeated item", "Không lặp món"), l("The one item cannot be taken twice.", "Không được lấy một món hai lần.")),
      test("zero", { items: [[1, 8]], capacity: 0 }, 0, l("Zero capacity", "Sức chứa bằng 0"), l("No positive-weight item fits.", "Không món có trọng lượng dương nào vừa.")),
      test("empty", { items: [], capacity: 7 }, 0, l("Empty items", "Không có món"), l("The empty subset has value zero.", "Tập rỗng có giá trị 0.")),
      test("greedy", { items: [[3, 5], [2, 3], [2, 3]], capacity: 4 }, 6, l("Greedy trap", "Bẫy tham lam"), l("Two weight-2 items beat the single value-5 item.", "Hai món trọng lượng 2 tốt hơn một món giá trị 5.")),
    ],
    hints: [l("Describe the best value achievable for each capacity.", "Mô tả giá trị tốt nhất với mỗi sức chứa."), l("For an item, either skip it or combine it with a smaller-capacity solution from before this item.", "Với mỗi món, bỏ qua hoặc ghép với lời giải sức chứa nhỏ hơn từ trước khi xét món này."), l("Use dp[0…capacity] = 0. For each [w,v], iterate c downwards from capacity to w and set dp[c] = max(dp[c], dp[c-w] + v).", "Dùng dp[0…capacity] = 0. Với [w,v], duyệt c giảm từ capacity tới w và đặt dp[c] = max(dp[c], dp[c-w] + v).")],
    complexity: l("Target: O(nC) time, O(C) space. This is pseudo-polynomial in numeric capacity C.", "Mục tiêu: O(nC) thời gian, O(C) bộ nhớ. Đây là độ phức tạp giả đa thức theo sức chứa C."),
  },
  {
    id: "regression-audit", version: 1, kind: "ml", difficulty: "medium", domainId: "machine-learning",
    title: l("Fit and audit a linear regressor", "Khớp và đánh giá hồi quy tuyến tính"), summary: l("Fit on training data only; report held-out MSE and MAE, then reason about leakage.", "Chỉ khớp trên dữ liệu huấn luyện; báo MSE, MAE trên tập kiểm tra và phân tích rò rỉ dữ liệu."),
    topicIds: ["linear-regression", "model-evaluation", "statistics"], algorithmIds: [], techniqueIds: ["cross-validation"],
    statement: l("Fit y = slope × x + intercept by ordinary least squares on train only. Compute mean squared error and mean absolute error on test. Each row is [x,y]. If all training x values are equal, use slope = 0 and intercept = mean(train y). Do not round. The numeric results are checked; the reflection rubric below is self-assessed, never automatically graded.", "Khớp y = slope × x + intercept bằng bình phương tối thiểu chỉ trên train. Tính sai số bình phương trung bình (MSE) và sai số tuyệt đối trung bình (MAE) trên test. Mỗi hàng là [x,y]. Nếu mọi x huấn luyện bằng nhau, dùng slope = 0, intercept = trung bình y huấn luyện. Không làm tròn. Kết quả số được chấm; phần lập luận theo rubric bên dưới do bạn tự đánh giá."),
    contract: l("solve({ train, test }) → { slope, intercept, mse, mae }. Every number must be finite; absolute/relative tolerance is 10⁻⁶.", "solve({ train, test }) → { slope, intercept, mse, mae }. Mọi số phải hữu hạn; sai số tuyệt đối/tương đối cho phép là 10⁻⁶."),
    constraints: [l("2 ≤ train.length ≤ 1,000; 1 ≤ test.length ≤ 1,000; finite coordinates in [-100,100].", "2 ≤ train.length ≤ 1.000; 1 ≤ test.length ≤ 1.000; tọa độ hữu hạn trong [-100,100].")],
    starters: {
      python: "def solve(data):\n    train, test = data[\"train\"], data[\"test\"]\n    return {\"slope\": 0, \"intercept\": 0, \"mse\": 0, \"mae\": 0}",
      javascript: "function solve({ train, test }) {\n  return { slope: 0, intercept: 0, mse: 0, mae: 0 };\n}",
    }, comparator: "numeric-tolerance",
    tests: [
      test("exact", { train: [[0, 1], [1, 3], [2, 5]], test: [[3, 7], [4, 9]] }, { slope: 2, intercept: 1, mse: 0, mae: 0 }, l("Exact line", "Đường thẳng chính xác"), l("The training line is y = 2x + 1 and both test points lie on it.", "Đường huấn luyện là y = 2x + 1 và cả hai điểm kiểm tra đều nằm trên đó.")),
      test("noise", { train: [[0, 0], [1, 1], [2, 2]], test: [[3, 4], [4, 2]] }, { slope: 1, intercept: 0, mse: 2.5, mae: 1.5 }, l("Held-out residuals", "Phần dư kiểm tra"), l("Predictions 3 and 4 give residuals -1 and 2: MSE = 2.5, MAE = 1.5.", "Dự đoán 3 và 4 cho phần dư -1 và 2: MSE = 2,5; MAE = 1,5.")),
      test("constant", { train: [[2, 1], [2, 3]], test: [[9, 4]] }, { slope: 0, intercept: 2, mse: 4, mae: 2 }, l("Constant feature", "Đặc trưng hằng"), l("The defined fallback predicts the training mean 2.", "Quy ước dự phòng dự đoán trung bình huấn luyện bằng 2.")),
      test("negative", { train: [[-1, 3], [0, 1], [1, -1]], test: [[2, -2], [3, -6]] }, { slope: -2, intercept: 1, mse: 1, mae: 1 }, l("Negative slope", "Hệ số góc âm"), l("Predictions -3 and -5 differ from labels by magnitude 1.", "Dự đoán -3 và -5 lệch nhãn với độ lớn 1.")),
    ],
    hints: [l("Center the training x and y values before estimating the slope.", "Trừ trung bình của x và y huấn luyện trước khi ước lượng hệ số góc."), l("slope = Σ((x−meanX)(y−meanY)) / Σ((x−meanX)²), intercept = meanY − slope × meanX.", "slope = Σ((x−meanX)(y−meanY)) / Σ((x−meanX)²), intercept = meanY − slope × meanX."), l("Use training means only. On test, average squared residuals for MSE and absolute residuals for MAE; divide by test.length, not train.length.", "Chỉ dùng trung bình train. Trên test, lấy trung bình bình phương phần dư cho MSE và trị tuyệt đối cho MAE; chia cho test.length, không phải train.length.")],
    complexity: l("O(n + m) time and O(1) extra space with separate accumulation passes. Numeric agreement says nothing about causal validity or generalization beyond these datasets.", "O(n + m) thời gian và O(1) bộ nhớ phụ với các lượt tích lũy riêng. Khớp kết quả số chưa chứng minh tính nhân quả hay khả năng khái quát ngoài các tập này."),
    rubric: [l("Explain why fitting or choosing a model using test labels leaks information.", "Giải thích vì sao khớp hoặc chọn mô hình bằng nhãn test gây rò rỉ thông tin."), l("Compare held-out MSE against predicting the training mean; distinguish improvement from overfitting.", "So sánh MSE kiểm tra với dự đoán trung bình train; phân biệt cải thiện và quá khớp."), l("Describe residual patterns that would suggest a nonlinear model or a bad split, and propose a separate validation split.", "Mô tả dạng phần dư gợi ý cần mô hình phi tuyến hoặc phép chia dữ liệu chưa tốt, và đề xuất tập validation riêng.")],
  },
];
export const practiceById = new Map(practiceProblems.map((problem) => [problem.id, problem]));
