import "server-only";
import { createHash } from "node:crypto";
import type { LearnLessonContent, LessonManifest, SubjectManifest } from "@/lib/domain/learn-platform";
import { parseLessonCandidate } from "@/lib/domain/learn-validation/parse";
import { parseSubjectManifest } from "@/lib/domain/learn-validation/subject";
import { AuthoringWriteError, writerLimits } from "./types.server";
import { safeToken, targetPath } from "./paths.server";
export const sha256 = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");

function ordered(value: unknown, depth = 0): unknown {
  if (depth > 32) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  if (Array.isArray(value)) return value.map((entry) => ordered(entry, depth + 1));
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined).sort(([left], [right]) => left.localeCompare(right, "en")).map(([key, entry]) => [key, ordered(entry, depth + 1)]));
  if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return value;
  throw new AuthoringWriteError("SERIALIZATION_FAILED");
}
export function canonicalJson(value: unknown): string {
  const text = JSON.stringify(ordered(value), null, 2) + "\n";
  if (Buffer.byteLength(text) > writerLimits.fileBytes) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  return text;
}
export function serializeSubject(subject: SubjectManifest): string {
  const result = parseSubjectManifest(subject);
  if (!result.subject) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  return canonicalJson(result.subject);
}
export function serializeBody(lesson: LessonManifest, body: LearnLessonContent): string {
  const result = parseLessonCandidate({ lesson, content: body });
  if (!result.candidate?.content) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  return canonicalJson(result.candidate.content);
}
export function generateSubjectIndex(subjectIds: readonly string[]): string {
  if (new Set(subjectIds).size !== subjectIds.length || subjectIds.some((id) => !safeToken(id))) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  const ids = [...subjectIds].sort();
  return '// Generated by canonical authoring serializer v1; DO NOT EDIT.\n' + ids.map((id, index) => `import subject${index} from "../subjects/${id}.json";\n`).join("") + `\nexport const learnSubjects = [${ids.map((_, index) => `subject${index}`).join(", ")}];\n`;
}
export function generateBodyIndex(lessons: readonly LessonManifest[]): string {
  const ids = lessons.map((lesson) => lesson.id).sort();
  if (new Set(ids).size !== ids.length) throw new AuthoringWriteError("SERIALIZATION_FAILED");
  return '// Generated by canonical authoring serializer v1; DO NOT EDIT.\n' + ids.map((id, index) => {
    const subjectId = id.split(":")[1];
    const relative = targetPath({ kind: "body", subjectId, lessonId: id }).replace("content/learn/", "../");
    return `import body${index} from "${relative}";\n`;
  }).join("") + `\nexport const learnLessonContent = [${ids.map((_, index) => `body${index}`).join(", ")}];\n`;
}
