import type { LearnExample } from "@/lib/domain/learn-platform";
const t = (en: string, vi = en) => ({ en, vi });
export const learnExamples: LearnExample[] = [
  {
    id: "python-example-first-program",
    subjectId: "python",
    lessonId: "learn:python:introduction",
    title: t("A small, observable program"),
    description: t("Bind a value, transform it, and print the result. Python execution is not enabled in this browser build."),
    language: "python",
    starterSource: "temperature_c = 21\ntemperature_f = temperature_c * 9 / 5 + 32\nprint(temperature_f)",
    runtime: "none",
    expectedOutput: "69.8",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "python-example-variables-state",
    subjectId: "python",
    lessonId: "learn:python:variables",
    title: t("Names refer to values"),
    description: t("Rebinding a name does not mutate the integer object previously referenced by that name."),
    language: "python",
    starterSource: "attempts = 1\nprevious = attempts\nattempts = attempts + 1\nprint(previous, attempts)",
    runtime: "none",
    expectedOutput: "1 2",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "python-example-string-slice",
    subjectId: "python",
    lessonId: "learn:python:strings",
    title: t("Slice without changing the source"),
    description: t("String slices create new strings; the original value remains unchanged."),
    language: "python",
    starterSource: "label = \"atlas\"\nfirst = label[:2]\nlast = label[-2:]\nprint(first, last, label)",
    runtime: "none",
    expectedOutput: "at as atlas",
    conceptIds: ["topic:strings"],
    difficulty: "easy",
  },
  {
    id: "python-example-list-aliasing",
    subjectId: "python",
    lessonId: "learn:python:lists",
    title: t("List aliasing is observable"),
    description: t("Two names can refer to the same mutable list. Use a copy when independent mutation is required."),
    language: "python",
    starterSource: "scores = [72, 88]\nalias = scores\ncopy = scores.copy()\nalias.append(95)\nprint(scores)\nprint(copy)",
    runtime: "none",
    expectedOutput: "[72, 88, 95]\n[72, 88]",
    conceptIds: ["topic:python", "topic:arrays"],
    difficulty: "easy",
  },
  {
    id: "python-example-function-contract",
    subjectId: "python",
    lessonId: "learn:python:functions",
    title: t("Make the contract visible"),
    description: t("A short function separates input validation from the value it computes."),
    language: "python",
    starterSource: "def average(values):\n    if not values:\n        raise ValueError(\"values must not be empty\")\n    return sum(values) / len(values)\n\nprint(average([4, 7, 10]))",
    runtime: "none",
    expectedOutput: "7.0",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "dsa-example-binary-search",
    subjectId: "dsa",
    lessonId: "learn:dsa:binary-search",
    title: t("Find the first matching position"),
    description: t("Edit the JavaScript implementation and run it against one public example in the existing QuickJS Worker."),
    language: "javascript",
    starterSource: "function solve(input) {\n  const { values, target } = input;\n  let low = 0;\n  let high = values.length;\n  while (low < high) {\n    const mid = low + Math.floor((high - low) / 2);\n    if (values[mid] < target) low = mid + 1;\n    else high = mid;\n  }\n  return low < values.length && values[low] === target ? low : -1;\n}",
    runtime: "browser-quickjs",
    input: { values: [1, 3, 3, 7, 9], target: 3 },
    expectedOutput: "1",
    conceptIds: ["topic:searching"],
    difficulty: "medium",
  },
  {
    id: "dsa-example-bfs",
    subjectId: "dsa",
    lessonId: "learn:dsa:graph-traversal",
    title: t("Breadth-first traversal order"),
    description: t("The queue makes discovery order explicit. Each vertex is marked when enqueued so it appears once."),
    language: "javascript",
    starterSource: "function solve(input) {\n  const { graph, start } = input;\n  const queue = [start];\n  const seen = new Set([start]);\n  const order = [];\n  for (let head = 0; head < queue.length; head += 1) {\n    const node = queue[head];\n    order.push(node);\n    for (const next of graph[node]) {\n      if (!seen.has(next)) { seen.add(next); queue.push(next); }\n    }\n  }\n  return order;\n}",
    runtime: "browser-quickjs",
    input: { graph: [[1, 2], [0, 3], [0], [1]], start: 0 },
    expectedOutput: "[0,1,2,3]",
    conceptIds: ["topic:graph-traversal"],
    difficulty: "medium",
  },
];
