import type { LearnExample, LearnLessonContent, LearnQuizQuestion, LearnReference } from "@/lib/domain/learn-platform";

const t = (en: string, vi = en) => ({ en, vi });

export const learnExamples: LearnExample[] = [
  {
    id: "python-example-first-program",
    subjectId: "python",
    lessonId: "learn:python:introduction",
    title: t("A small, observable program"),
    description: t("Bind a value, transform it, and print the result. Python execution is not enabled in this browser build."),
    language: "python",
    starterSource: "temperature_c = 21\ntemperature_f = temperature_c * 9 / 5 + 32\nprint(temperature_f)",
    runtime: "none",
    expectedOutput: "69.8",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "python-example-variables-state",
    subjectId: "python",
    lessonId: "learn:python:variables",
    title: t("Names refer to values"),
    description: t("Rebinding a name does not mutate the integer object previously referenced by that name."),
    language: "python",
    starterSource: "attempts = 1\nprevious = attempts\nattempts = attempts + 1\nprint(previous, attempts)",
    runtime: "none",
    expectedOutput: "1 2",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "python-example-string-slice",
    subjectId: "python",
    lessonId: "learn:python:strings",
    title: t("Slice without changing the source"),
    description: t("String slices create new strings; the original value remains unchanged."),
    language: "python",
    starterSource: "label = \"atlas\"\nfirst = label[:2]\nlast = label[-2:]\nprint(first, last, label)",
    runtime: "none",
    expectedOutput: "at as atlas",
    conceptIds: ["topic:strings"],
    difficulty: "easy",
  },
  {
    id: "python-example-list-aliasing",
    subjectId: "python",
    lessonId: "learn:python:lists",
    title: t("List aliasing is observable"),
    description: t("Two names can refer to the same mutable list. Use a copy when independent mutation is required."),
    language: "python",
    starterSource: "scores = [72, 88]\nalias = scores\ncopy = scores.copy()\nalias.append(95)\nprint(scores)\nprint(copy)",
    runtime: "none",
    expectedOutput: "[72, 88, 95]\n[72, 88]",
    conceptIds: ["topic:python", "topic:arrays"],
    difficulty: "easy",
  },
  {
    id: "python-example-function-contract",
    subjectId: "python",
    lessonId: "learn:python:functions",
    title: t("Make the contract visible"),
    description: t("A short function separates input validation from the value it computes."),
    language: "python",
    starterSource: "def average(values):\n    if not values:\n        raise ValueError(\"values must not be empty\")\n    return sum(values) / len(values)\n\nprint(average([4, 7, 10]))",
    runtime: "none",
    expectedOutput: "7.0",
    conceptIds: ["topic:python"],
    difficulty: "easy",
  },
  {
    id: "dsa-example-binary-search",
    subjectId: "dsa",
    lessonId: "learn:dsa:binary-search",
    title: t("Find the first matching position"),
    description: t("Edit the JavaScript implementation and run it against one public example in the existing QuickJS Worker."),
    language: "javascript",
    starterSource: "function solve(input) {\n  const { values, target } = input;\n  let low = 0;\n  let high = values.length;\n  while (low < high) {\n    const mid = low + Math.floor((high - low) / 2);\n    if (values[mid] < target) low = mid + 1;\n    else high = mid;\n  }\n  return low < values.length && values[low] === target ? low : -1;\n}",
    runtime: "browser-quickjs",
    input: { values: [1, 3, 3, 7, 9], target: 3 },
    expectedOutput: "1",
    conceptIds: ["topic:searching"],
    difficulty: "medium",
  },
  {
    id: "dsa-example-bfs",
    subjectId: "dsa",
    lessonId: "learn:dsa:graph-traversal",
    title: t("Breadth-first traversal order"),
    description: t("The queue makes discovery order explicit. Each vertex is marked when enqueued so it appears once."),
    language: "javascript",
    starterSource: "function solve(input) {\n  const { graph, start } = input;\n  const queue = [start];\n  const seen = new Set([start]);\n  const order = [];\n  for (let head = 0; head < queue.length; head += 1) {\n    const node = queue[head];\n    order.push(node);\n    for (const next of graph[node]) {\n      if (!seen.has(next)) { seen.add(next); queue.push(next); }\n    }\n  }\n  return order;\n}",
    runtime: "browser-quickjs",
    input: { graph: [[1, 2], [0, 3], [0], [1]], start: 0 },
    expectedOutput: "[0,1,2,3]",
    conceptIds: ["topic:graph-traversal"],
    difficulty: "medium",
  },
];

export const learnReferences: LearnReference[] = [
  { id: "python-ref-len", subjectId: "python", categoryId: "python-builtins", slug: "len", name: "len", signature: "len(value)", description: t("Return the number of items in a sized value."), relatedLessonIds: ["learn:python:strings", "learn:python:lists"], conceptIds: ["topic:python"] },
  { id: "python-ref-range", subjectId: "python", categoryId: "python-builtins", slug: "range", name: "range", signature: "range(start, stop, step)", description: t("Create an immutable arithmetic progression used commonly for iteration."), relatedLessonIds: ["learn:python:functions"], conceptIds: ["topic:python"] },
  { id: "python-ref-enumerate", subjectId: "python", categoryId: "python-builtins", slug: "enumerate", name: "enumerate", signature: "enumerate(iterable, start=0)", description: t("Pair each item from an iterable with a counter."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python"] },
  { id: "python-ref-list-append", subjectId: "python", categoryId: "python-list-methods", slug: "list-append", name: "list.append", signature: "items.append(value)", description: t("Add one value to the end of a list in place."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:arrays"] },
  { id: "python-ref-list-pop", subjectId: "python", categoryId: "python-list-methods", slug: "list-pop", name: "list.pop", signature: "items.pop(index=-1)", description: t("Remove and return the item at an index, defaulting to the last item."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:arrays"] },
  { id: "python-ref-list-sort", subjectId: "python", categoryId: "python-list-methods", slug: "list-sort", name: "list.sort", signature: "items.sort(*, key=None, reverse=False)", description: t("Sort a list in place and return no value."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:sorting"] },
  { id: "dsa-ref-growth-rates", subjectId: "dsa", categoryId: "dsa-complexity", slug: "growth-rates", name: "Common growth rates", description: t("A compact ordering of constant, logarithmic, linear, linearithmic, polynomial, exponential, and factorial growth."), relatedLessonIds: ["learn:dsa:complexity"], conceptIds: ["topic:complexity-analysis"] },
  { id: "dsa-ref-search-complexity", subjectId: "dsa", categoryId: "dsa-complexity", slug: "search-complexity", name: "Search complexity", description: t("Compare linear scanning with binary search and hash-based lookup under their required assumptions."), relatedLessonIds: ["learn:dsa:binary-search"], conceptIds: ["topic:searching", "topic:hash-tables"] },
];

export const learnQuizQuestions: LearnQuizQuestion[] = [
  { id: "python-quiz-dynamic-types", prompt: t("In Python, where is the type associated?"), options: [{ id: "name", text: t("The variable name") }, { id: "value", text: t("The runtime value") }, { id: "file", text: t("The source file") }], correctOptionId: "value", explanation: t("Names bind to objects; the objects carry runtime type information."), conceptId: "topic:python" },
  { id: "python-quiz-string-index", prompt: t("What does a negative string index count from?"), options: [{ id: "start", text: t("The start") }, { id: "end", text: t("The end") }, { id: "middle", text: t("The middle") }], correctOptionId: "end", explanation: t("Index -1 refers to the final element."), conceptId: "topic:strings" },
  { id: "python-quiz-list-mutation", prompt: t("Which operation mutates an existing list?"), options: [{ id: "append", text: t("items.append(value)") }, { id: "slice", text: t("items[:]") }, { id: "concat", text: t("items + [value]") }], correctOptionId: "append", explanation: t("append changes the list object in place."), conceptId: "topic:python" },
  { id: "dsa-quiz-binary-search", prompt: t("Which invariant does ordinary binary search require?"), options: [{ id: "sorted", text: t("The search range is ordered") }, { id: "unique", text: t("Every value is unique") }, { id: "positive", text: t("Every value is positive") }], correctOptionId: "sorted", explanation: t("The comparison at the midpoint is useful only when it safely discards an ordered half."), conceptId: "topic:searching" },
  { id: "dsa-quiz-growth", prompt: t("Which grows more slowly as n becomes large?"), options: [{ id: "log", text: t("log n") }, { id: "linear", text: t("n") }, { id: "quadratic", text: t("n²") }], correctOptionId: "log", explanation: t("Logarithmic growth increases by a constant amount when input size is multiplied."), conceptId: "topic:complexity-analysis" },
];

export const learnLessonContent: LearnLessonContent[] = [
  {
    lessonId: "learn:python:introduction", version: 1, reviewedAt: "2026-09-30", summary: t("Understand Python's execution model, strengths, and the boundary between readable syntax and runtime behavior."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Explain how a Python source file becomes executed instructions."), t("Distinguish syntax, values, names, and side effects."), t("Run a small program with observable output in an approved Python environment.")] },
      { id: "model", type: "definition", term: "Python program", body: t("A sequence of statements evaluated by a Python implementation. Statements may bind names, compute values, control execution, define reusable behavior, or interact with the outside world.") },
      { id: "execution", type: "paragraph", title: t("A useful execution model"), body: t("Read a program from top to bottom while tracking the current bindings and control flow. When a function is called, create a new local scope; when an exception is raised, follow the active handling path. This model is more durable than memorizing punctuation.") },
      { id: "syntax", type: "syntax", language: "python", code: "name = expression\nprint(name)" },
      { id: "example", type: "example", exampleId: "python-example-first-program" },
      { id: "note", type: "callout", tone: "important", body: t("Python source is editable here, but this Atlas build does not claim an approved Python runtime. Use the displayed output as authored material or open an external/local Python environment.") },
      { id: "mistake", type: "callout", tone: "common-mistake", body: t("Readable syntax does not remove the need to reason about types, mutation, exceptions, and algorithmic cost.") },
      { id: "related", type: "related", lessonIds: ["learn:python:variables", "learn:python:strings"], problemIds: [] },
    ],
  },
  {
    lessonId: "learn:python:variables", version: 1, reviewedAt: "2026-09-30", summary: t("Reason about names as bindings to values, including rebinding, identity, scope, and naming discipline."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Bind and rebind names."), t("Distinguish equality from identity."), t("Choose names that expose intent and scope.")] },
      { id: "definition", type: "definition", term: "Binding", body: t("An association between a name and an object in a namespace. Assignment changes a binding; it does not declare a permanent type for the name.") },
      { id: "assignment", type: "syntax", language: "python", code: "name = value\nleft, right = right, left" },
      { id: "example", type: "example", exampleId: "python-example-variables-state" },
      { id: "compare", type: "comparison", columns: [t("Question"), t("Operator")], rows: [{ label: t("Do these values compare equal?"), values: [t("=="), t("Value semantics")] }, { label: t("Are these references the same object?"), values: [t("is"), t("Identity semantics")] }] },
      { id: "tip", type: "callout", tone: "tip", body: t("Prefer one clear binding per line. Use unpacking when the parallel structure is part of the idea, not merely to shorten the file.") },
      { id: "related", type: "related", lessonIds: ["learn:python:strings", "learn:python:lists"], problemIds: [] },
    ],
  },
  {
    lessonId: "learn:python:strings", version: 1, reviewedAt: "2026-09-30", summary: t("Use Python strings as immutable sequences while accounting for indexing, slicing, encoding, and construction cost."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Index and slice strings safely."), t("Explain string immutability."), t("Select formatting and joining operations deliberately.")] },
      { id: "definition", type: "definition", term: "String", body: t("An immutable sequence of Unicode code points. Indexing returns a one-character string; slicing returns a new string.") },
      { id: "syntax", type: "syntax", language: "python", code: "text[index]\ntext[start:stop:step]\nf\"value={value}\"" },
      { id: "example", type: "example", exampleId: "python-example-string-slice" },
      { id: "table", type: "table", columns: [t("Operation"), t("Meaning")], rows: [["text[0]", "first item"], ["text[-1]", "last item"], ["text[:k]", "prefix before k"], ["separator.join(parts)", "combine many pieces once"]] },
      { id: "mistake", type: "callout", tone: "common-mistake", body: t("Repeated string concatenation inside a large loop may allocate many intermediate strings. Accumulate parts and join when scale matters.") },
      { id: "refs", type: "references", referenceIds: ["python-ref-len"] },
    ],
  },
  {
    lessonId: "learn:python:lists", version: 1, reviewedAt: "2026-09-30", summary: t("Use lists as ordered mutable sequences and reason explicitly about aliasing, copying, mutation, and traversal."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Read and update list items."), t("Predict aliasing and copying behavior."), t("Choose iteration patterns that remain correct during mutation.")] },
      { id: "definition", type: "definition", term: "List", body: t("A mutable ordered container that stores references to objects. A list can grow, shrink, and contain values of different runtime types.") },
      { id: "syntax", type: "syntax", language: "python", code: "items = [first, second]\nitems.append(value)\ncopy = items.copy()" },
      { id: "example", type: "example", exampleId: "python-example-list-aliasing" },
      { id: "cost", type: "table", columns: [t("Operation"), t("Typical cost")], rows: [["items[index]", "O(1)"], ["items.append(value)", "amortized O(1)"], ["items.insert(0, value)", "O(n)"], ["value in items", "O(n)"]] },
      { id: "warning", type: "callout", tone: "warning", body: t("Do not remove arbitrary items from the same list you are iterating unless the algorithm is designed around changing indices. Filter into a new list or iterate over a copy.") },
      { id: "refs", type: "references", referenceIds: ["python-ref-list-append", "python-ref-list-pop", "python-ref-list-sort", "python-ref-enumerate"] },
      { id: "related", type: "related", lessonIds: ["learn:dsa:arrays", "learn:python:functions"], problemIds: [] },
    ],
  },
  {
    lessonId: "learn:python:functions", version: 1, reviewedAt: "2026-09-30", summary: t("Design functions as explicit contracts with inputs, outputs, failure behavior, and a focused responsibility."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Define and call a function."), t("Distinguish parameters from arguments."), t("Design a predictable return and error contract.")] },
      { id: "definition", type: "definition", term: "Function", body: t("A reusable callable object that binds arguments to parameters, executes a body in a local scope, and returns a value or raises an exception.") },
      { id: "syntax", type: "syntax", language: "python", code: "def name(parameter, optional=default):\n    \"\"\"Describe the contract.\"\"\"\n    return result" },
      { id: "example", type: "example", exampleId: "python-example-function-contract" },
      { id: "practice", type: "list", ordered: true, items: [t("State the input domain."), t("Choose a return shape that callers can rely on."), t("Reject invalid input deliberately."), t("Keep side effects visible in the name or interface.")] },
      { id: "mistake", type: "callout", tone: "common-mistake", body: t("A function that sometimes returns a value and sometimes falls through to None creates a hidden union that every caller must handle.") },
      { id: "refs", type: "references", referenceIds: ["python-ref-len", "python-ref-range"] },
    ],
  },
  {
    lessonId: "learn:dsa:complexity", version: 1, reviewedAt: "2026-09-30", summary: t("Describe how resource use grows, state the input model, and separate upper, lower, tight, worst-case, and amortized claims."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Define the input-size variable."), t("Derive a dominant growth term."), t("Distinguish O, Ω, and Θ claims.")] },
      { id: "definition", type: "definition", term: "Asymptotic complexity", body: t("A description of resource growth as input size increases, abstracting away constant factors and lower-order terms under a stated computation model.") },
      { id: "bounds", type: "comparison", columns: [t("Meaning"), t("Use")], rows: [{ label: t("O(g(n))"), values: [t("Asymptotic upper bound"), t("The cost eventually grows no faster than a constant multiple of g") ] }, { label: t("Ω(g(n))"), values: [t("Asymptotic lower bound"), t("The cost eventually grows at least as fast as g")] }, { label: t("Θ(g(n))"), values: [t("Tight bound"), t("Both upper and lower bounds hold")] }] },
      { id: "method", type: "list", ordered: true, items: [t("Choose n and the operation to count."), t("Count work by case or iteration."), t("Simplify the expression without hiding relevant variables."), t("State worst, average, best, expected, or amortized context.")] },
      { id: "warning", type: "callout", tone: "important", body: t("Big O is not automatically worst case. O describes an upper bound; the case must be stated separately.") },
      { id: "refs", type: "references", referenceIds: ["dsa-ref-growth-rates"] },
    ],
  },
  {
    lessonId: "learn:dsa:arrays", version: 1, reviewedAt: "2026-09-30", summary: t("Model contiguous indexed storage, distinguish logical length from capacity, and predict the cost of access and shifting."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Explain constant-time index access."), t("Predict insertion and deletion costs."), t("Choose traversal invariants that avoid index errors.")] },
      { id: "definition", type: "definition", term: "Array", body: t("A sequence whose elements occupy regular positions in memory, allowing an index to be translated into an address with constant arithmetic.") },
      { id: "formula", type: "syntax", language: "text", code: "address(i) = base + i × element_size" },
      { id: "cost", type: "table", columns: [t("Operation"), t("Cost"), t("Reason")], rows: [["read/write by index", "O(1)", "direct address calculation"], ["scan", "O(n)", "inspect up to n items"], ["insert at front", "O(n)", "shift existing items"], ["append to dynamic array", "amortized O(1)", "occasional resize"]] },
      { id: "exercise", type: "exercise", exerciseId: "exercise:array-linear-scan" },
      { id: "mistake", type: "callout", tone: "common-mistake", body: t("A dynamic array may have spare capacity, but indices at or beyond its logical length are still invalid.") },
      { id: "related", type: "related", lessonIds: ["learn:dsa:binary-search", "learn:python:lists"], problemIds: ["first-occurrence"] },
    ],
  },
  {
    lessonId: "learn:dsa:binary-search", version: 1, reviewedAt: "2026-09-30", summary: t("Maintain a search-space invariant and discard half of an ordered domain on each iteration."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("State the ordering assumption."), t("Choose inclusive or half-open boundaries consistently."), t("Implement lower-bound search without overflow or infinite loops.")] },
      { id: "definition", type: "definition", term: "Binary search", body: t("A family of algorithms that locate a boundary in a monotone search space by testing a midpoint and preserving the half that can still contain the answer.") },
      { id: "invariant", type: "callout", tone: "important", body: t("In the half-open form [low, high), the answer is never outside the interval. Each branch must shrink that interval.") },
      { id: "example", type: "example", exampleId: "dsa-example-binary-search" },
      { id: "complexity", type: "complexity", time: "O(log n)", space: "O(1)", body: t("Each iteration reduces the remaining interval by roughly half while storing only boundary indices.") },
      { id: "mistake", type: "callout", tone: "common-mistake", body: t("Mixing inclusive and exclusive boundary rules is the most common source of missed elements and non-terminating loops. Write the invariant before the code.") },
      { id: "refs", type: "references", referenceIds: ["dsa-ref-search-complexity"] },
      { id: "related", type: "related", lessonIds: ["learn:dsa:arrays", "learn:dsa:lower-and-upper-bound"], problemIds: ["first-occurrence"] },
    ],
  },
  {
    lessonId: "learn:dsa:graph-traversal", version: 1, reviewedAt: "2026-09-30", summary: t("Traverse graph state with an explicit frontier, a visited invariant, and a representation chosen for the workload."),
    blocks: [
      { id: "objectives", type: "objectives", items: [t("Represent a sparse graph with adjacency lists."), t("Explain BFS and DFS frontier behavior."), t("Prevent duplicate processing with a visited invariant.")] },
      { id: "definition", type: "definition", term: "Graph traversal", body: t("A systematic process for discovering reachable vertices and examining edges while preventing repeated expansion of already discovered state.") },
      { id: "compare", type: "comparison", columns: [t("Frontier"), t("Useful property")], rows: [{ label: t("BFS"), values: [t("Queue"), t("Nondecreasing unweighted distance")] }, { label: t("DFS"), values: [t("Stack or recursion"), t("Deep exploration and structural finishing order")] }] },
      { id: "example", type: "example", exampleId: "dsa-example-bfs" },
      { id: "complexity", type: "complexity", time: "O(V + E)", space: "O(V)", body: t("With adjacency lists, each reachable vertex is enqueued once and each outgoing edge is examined once.") },
      { id: "warning", type: "callout", tone: "warning", body: t("Mark a vertex when it enters the frontier, not after it leaves, or the same vertex may be queued many times.") },
      { id: "related", type: "related", lessonIds: ["learn:dsa:graph-representation", "learn:dsa:bfs-shortest-path"], problemIds: ["unweighted-distance"] },
    ],
  },
];

export const learnContentByLessonId = new Map(learnLessonContent.map((item) => [item.lessonId, item]));
export const learnExampleById = new Map(learnExamples.map((item) => [item.id, item]));
export const learnReferenceById = new Map(learnReferences.map((item) => [item.id, item]));
export const learnReferenceByRoute = new Map(learnReferences.map((item) => [`${item.subjectId}/${item.slug}`, item]));
export const learnQuizQuestionById = new Map(learnQuizQuestions.map((item) => [item.id, item]));
