import type { LearnQuizQuestion } from "@/lib/domain/learn-platform";
const t = (en: string, vi = en) => ({ en, vi });
export const learnQuizQuestions: LearnQuizQuestion[] = [
  { id: "python-quiz-dynamic-types", prompt: t("In Python, where is the type associated?"), options: [{ id: "name", text: t("The variable name") }, { id: "value", text: t("The runtime value") }, { id: "file", text: t("The source file") }], correctOptionId: "value", explanation: t("Names bind to objects; the objects carry runtime type information."), conceptId: "topic:python" },
  { id: "python-quiz-string-index", prompt: t("What does a negative string index count from?"), options: [{ id: "start", text: t("The start") }, { id: "end", text: t("The end") }, { id: "middle", text: t("The middle") }], correctOptionId: "end", explanation: t("Index -1 refers to the final element."), conceptId: "topic:strings" },
  { id: "python-quiz-list-mutation", prompt: t("Which operation mutates an existing list?"), options: [{ id: "append", text: t("items.append(value)") }, { id: "slice", text: t("items[:]") }, { id: "concat", text: t("items + [value]") }], correctOptionId: "append", explanation: t("append changes the list object in place."), conceptId: "topic:python" },
  { id: "dsa-quiz-binary-search", prompt: t("Which invariant does ordinary binary search require?"), options: [{ id: "sorted", text: t("The search range is ordered") }, { id: "unique", text: t("Every value is unique") }, { id: "positive", text: t("Every value is positive") }], correctOptionId: "sorted", explanation: t("The comparison at the midpoint is useful only when it safely discards an ordered half."), conceptId: "topic:searching" },
  { id: "dsa-quiz-growth", prompt: t("Which grows more slowly as n becomes large?"), options: [{ id: "log", text: t("log n") }, { id: "linear", text: t("n") }, { id: "quadratic", text: t("n²") }], correctOptionId: "log", explanation: t("Logarithmic growth increases by a constant amount when input size is multiplied."), conceptId: "topic:complexity-analysis" },
];
