import type { LearnReference } from "@/lib/domain/learn-platform";
const t = (en: string, vi = en) => ({ en, vi });
export const learnReferences: LearnReference[] = [
  { id: "python-ref-len", subjectId: "python", categoryId: "python-builtins", slug: "len", name: "len", signature: "len(value)", description: t("Return the number of items in a sized value."), relatedLessonIds: ["learn:python:strings", "learn:python:lists"], conceptIds: ["topic:python"] },
  { id: "python-ref-range", subjectId: "python", categoryId: "python-builtins", slug: "range", name: "range", signature: "range(start, stop, step)", description: t("Create an immutable arithmetic progression used commonly for iteration."), relatedLessonIds: ["learn:python:functions"], conceptIds: ["topic:python"] },
  { id: "python-ref-enumerate", subjectId: "python", categoryId: "python-builtins", slug: "enumerate", name: "enumerate", signature: "enumerate(iterable, start=0)", description: t("Pair each item from an iterable with a counter."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python"] },
  { id: "python-ref-list-append", subjectId: "python", categoryId: "python-list-methods", slug: "list-append", name: "list.append", signature: "items.append(value)", description: t("Add one value to the end of a list in place."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:arrays"] },
  { id: "python-ref-list-pop", subjectId: "python", categoryId: "python-list-methods", slug: "list-pop", name: "list.pop", signature: "items.pop(index=-1)", description: t("Remove and return the item at an index, defaulting to the last item."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:arrays"] },
  { id: "python-ref-list-sort", subjectId: "python", categoryId: "python-list-methods", slug: "list-sort", name: "list.sort", signature: "items.sort(*, key=None, reverse=False)", description: t("Sort a list in place and return no value."), relatedLessonIds: ["learn:python:lists"], conceptIds: ["topic:python", "topic:sorting"] },
  { id: "dsa-ref-growth-rates", subjectId: "dsa", categoryId: "dsa-complexity", slug: "growth-rates", name: "Common growth rates", description: t("A compact ordering of constant, logarithmic, linear, linearithmic, polynomial, exponential, and factorial growth."), relatedLessonIds: ["learn:dsa:complexity"], conceptIds: ["topic:complexity-analysis"] },
  { id: "dsa-ref-search-complexity", subjectId: "dsa", categoryId: "dsa-complexity", slug: "search-complexity", name: "Search complexity", description: t("Compare linear scanning with binary search and hash-based lookup under their required assumptions."), relatedLessonIds: ["learn:dsa:binary-search"], conceptIds: ["topic:searching", "topic:hash-tables"] },
];
