import type { ContentBlock, GlossaryTerm, LearningObjective } from "@/lib/types";

export interface DeepTopicTranslation {
  objectives: LearningObjective[];
  glossary: GlossaryTerm[];
  content: ContentBlock[];
}

const objectives = (topicId: string, descriptions: string[]): LearningObjective[] =>
  descriptions.map((description, index) => ({ id: `${topicId}-objective-${index + 1}`, description }));

const complexity: DeepTopicTranslation = {
  objectives: objectives("complexity-analysis", [
    "Phân biệt kích thước đầu vào với giá trị số của đầu vào.",
    "Đếm phép toán chi phối trong thủ tục lặp và đệ quy.",
    "Sử dụng đúng ý nghĩa toán học của O, Ω và Θ.",
    "Phân biệt phân tích trường hợp xấu nhất, trung bình, kỳ vọng và khấu hao.",
    "So sánh tốc độ tăng trưởng mà chỉ lược bỏ hằng số và số hạng bậc thấp.",
    "Nhận ra giả định mô hình bị ẩn trong một phát biểu về độ phức tạp.",
  ]),
  glossary: [
    { term: "Kích thước đầu vào", definition: "Đại lượng đo lượng thông tin của đầu vào, thường là số phần tử hoặc số bit cần để mã hóa." },
    { term: "Cận tiệm cận", definition: "Phát biểu về tốc độ tăng sau một ngưỡng đầu vào đủ lớn, độc lập với hệ số hằng phụ thuộc máy." },
    { term: "Chi phí khấu hao", definition: "Chi phí trung bình mỗi thao tác trên một chuỗi thao tác xấu nhất, không cần giả định phân phối xác suất." },
  ],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Mục tiêu học tập", objectives: ["Mô hình hóa chi phí theo kích thước đầu vào", "Chứng minh các cận tiệm cận cơ bản", "Phân tích vòng lặp, đệ quy và chuỗi thao tác", "Nêu rõ giả định đứng sau kết quả phân tích"] },
    { type: "intuition", id: "intuition", title: "Vì sao tốc độ tăng trưởng quan trọng", body: "Thời gian tính bằng mili giây gắn với một máy và một bộ dữ liệu cụ thể. Phân tích độ phức tạp đặt câu hỏi bền vững hơn: lượng công việc tăng nhanh đến đâu khi bài toán lớn lên? Máy nhanh hơn 100 lần cũng không cứu được thuật toán mũ trong thời gian dài, trong khi thuật toán tuyến tính thường mở rộng dự đoán được.", analogy: "Độ phức tạp là hình dạng của đường cong chi phí, không phải một con số trên đồng hồ bấm giờ." },
    { type: "definition", id: "cost-model", title: "Chọn mô hình chi phí", term: "Mô hình RAM", definition: "Mô hình máy đơn giản hóa, trong đó số học cơ bản, so sánh, gán và truy cập bộ nhớ theo chỉ số có thời gian hằng số. Mô hình chỉ hữu ích khi các giả định phù hợp với quy mô bài toán.", notation: "T(n): số phép toán cơ bản trên đầu vào kích thước n", citations: [{ sourceId: "clrs-4e", locator: "Chương 2" }] },
    { type: "formula", id: "asymptotic-notation", title: "Ký hiệu tiệm cận", expression: "0 ≤ c₁g(n) ≤ f(n) ≤ c₂g(n), for every n ≥ n₀", description: "Bất đẳng thức này định nghĩa f(n) ∈ Θ(g(n)). Big-O chỉ giữ cận trên; Ω chỉ giữ cận dưới.", terms: [{ symbol: "f(n)", meaning: "Chi phí đang được phân tích" }, { symbol: "g(n)", meaning: "Hàm tăng trưởng dùng để so sánh" }, { symbol: "c₁, c₂", meaning: "Các hệ số dương không đổi" }, { symbol: "n₀", meaning: "Ngưỡng mà từ đó cận luôn đúng" }], citations: [{ sourceId: "clrs-4e", locator: "Chương 3" }] },
    { type: "worked-example", id: "loop-example", title: "Ví dụ: vòng lặp tam giác", problem: "Phân tích vòng lặp lồng nhau: với mỗi i từ 0 đến n − 1, vòng trong chạy từ 0 đến i.", steps: [{ title: "Đếm số lần lặp bên trong", explanation: "Với i cố định, thân vòng trong chạy i + 1 lần.", formula: "1 + 2 + ⋯ + n" }, { title: "Tính tổng", explanation: "Công thức cấp số cộng cho số lần chính xác.", formula: "n(n + 1) / 2 = n²/2 + n/2" }, { title: "Rút ra tốc độ tăng", explanation: "Số hạng n² chi phối; hệ số hằng và số hạng n không đổi lớp tiệm cận.", formula: "T(n) ∈ Θ(n²)" }], conclusion: "Không thể kết luận Θ(n²) chỉ vì có hai vòng lặp; kết quả đến từ tổng số lần thực thi." },
    { type: "worked-example", id: "binary-example", title: "Ví dụ: liên tục chia đôi", problem: "Một vòng lặp thay n bằng floor(n / 2) cho đến khi n bằng 1. Nó chạy bao nhiêu lần?", steps: [{ title: "Viết trạng thái sau k bước", explanation: "Tạm bỏ phép làm tròn để lập cận, giá trị còn lại là n / 2ᵏ.", formula: "nₖ ≈ n / 2ᵏ" }, { title: "Giải điều kiện dừng", explanation: "Vòng lặp dừng khi giá trị còn lại không quá 1.", formula: "n / 2ᵏ ≤ 1 ⇒ 2ᵏ ≥ n" }, { title: "Lấy logarithm", explanation: "k nhỏ nhất phù hợp là trần của log cơ số 2 của n.", formula: "k = ⌈log₂ n⌉" }], conclusion: "Liên tục nhân hoặc chia cho một hằng số thường tạo ra độ sâu logarithm." },
    { type: "key-idea", id: "analysis-method", title: "Quy trình phân tích có thể lặp lại", body: "Phân tích từ cấu trúc điều khiển và bất biến của thuật toán, không dựa vào nhãn đã học thuộc.", points: ["Định nghĩa chính xác biến kích thước đầu vào.", "Chọn phép toán hoặc tài nguyên cần đếm.", "Biểu diễn số đếm bằng tổng hoặc truy hồi.", "Giải hoặc chặn biểu thức đó.", "Nêu trường hợp đang xét và giả định mô hình máy."] },
    { type: "comparison", id: "growth-comparison", title: "Các mốc tốc độ tăng", columns: ["Diễn giải điển hình", "Hành vi khi tăng quy mô"], rows: [{ label: "Θ(1)", values: ["Truy cập trực tiếp hoặc lượng việc bị chặn", "Không đổi theo n trong mô hình"] }, { label: "Θ(log n)", values: ["Thu nhỏ theo một hệ số cố định", "n gấp đôi chỉ thêm một bước"] }, { label: "Θ(n)", values: ["Duyệt mỗi phần tử một lần", "n gấp đôi thì chi phí gấp đôi"] }, { label: "Θ(n log n)", values: ["Chia cân bằng rồi kết hợp", "Gần tuyến tính ở quy mô thực tế"] }, { label: "Θ(n²)", values: ["Xét mọi cặp hoặc quét lồng nhau", "n gấp đôi thì chi phí gấp bốn"] }, { label: "Θ(2ⁿ)", values: ["Liệt kê các tập con", "Nhanh chóng trở nên bất khả thi"] }] },
    { type: "complexity", id: "cases", title: "Các trường hợp và chi phí tổng hợp", time: "Phụ thuộc thuật toán và trường hợp được chọn", space: "Bộ nhớ phụ không gồm dữ liệu đầu vào, trừ khi nêu khác", analysis: "Cận xấu nhất là một bảo đảm; cận trung bình cần phân phối đầu vào; cận kỳ vọng có thể đến từ lựa chọn ngẫu nhiên của thuật toán; cận khấu hao bao phủ toàn bộ chuỗi thao tác.", cases: [{ name: "Xấu nhất", complexity: "max trên mọi đầu vào kích thước n", reason: "Cung cấp bảo đảm" }, { name: "Trung bình", complexity: "kỳ vọng trên đầu vào", reason: "Cần nêu phân phối" }, { name: "Khấu hao", complexity: "chi phí chuỗi / số thao tác", reason: "Giải thích thao tác đắt xuất hiện không thường xuyên" }] },
    { type: "common-mistakes", id: "mistakes", title: "Lỗi thường gặp", mistakes: [{ mistake: "Đếm số vòng lặp thay vì số lần lặp", consequence: "Hai vòng lồng nhau bị gán nhầm là bậc hai dù miền vòng trong bị chặn.", correction: "Cộng số lần thực tế của phép toán chi phối." }, { mistake: "Xem Big-O như thời gian chạy chính xác", consequence: "O(n²) bị hiểu thành luôn chậm hơn O(n).", correction: "Big-O là cận trên về lâu dài; hằng số, miền đầu vào và triển khai vẫn quan trọng." }, { mistake: "Nhầm phân tích khấu hao với trường hợp trung bình", consequence: "Bảo đảm trên mọi chuỗi thao tác bị trộn với một mô hình xác suất.", correction: "Nêu rõ tính ngẫu nhiên đến từ đầu vào, thuật toán hay không có." }] },
    { type: "exercise", id: "ex-loop", title: "Bài tập: vòng lặp phụ thuộc", exerciseType: "calculation", difficulty: "easy", prompt: "Vòng lặp cho i từ 1 đến n và thực hiện floor(n / i) phép toán hằng số. Hãy cho cận tiệm cận chặt.", hints: ["Viết tổng chi phí.", "So sánh với chuỗi điều hòa."], solution: "Chi phí là Σᵢ₌₁ⁿ floor(n/i). Bỏ floor làm tổng thay đổi không quá n; nΣ(1/i) = nHₙ. Vì Hₙ ∈ Θ(log n), tổng là Θ(n log n).", explanation: "Khối lượng vòng trong không hằng và không theo tam giác; nó theo dạng điều hòa.", relatedTopicIds: ["complexity-analysis"], estimatedMinutes: 12 },
    { type: "exercise", id: "ex-recursion", title: "Bài tập: chi phí đệ quy", exerciseType: "calculation", difficulty: "medium", prompt: "Giải T(n) = 2T(n/2) + n với T(1) = Θ(1).", hints: ["Vẽ cây đệ quy.", "Tính tổng công việc ngoài đệ quy ở mỗi tầng."], solution: "Mỗi tầng thực hiện Θ(n) công việc kết hợp. Có log₂n + 1 tầng, nên T(n) ∈ Θ(n log n).", explanation: "Số bài toán con tăng trong khi kích thước từng bài giảm; tổng công việc mỗi tầng vẫn tuyến tính.", relatedTopicIds: ["recursion", "sorting"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-claim", title: "Bài tập: phản biện một khẳng định", exerciseType: "proof", difficulty: "hard", prompt: "Một lập trình viên nói 2ⁿ là O(1.99ⁿ) vì hai cơ số gần nhau. Hãy chứng minh hoặc bác bỏ.", hints: ["Xét tỷ số 2ⁿ/1.99ⁿ.", "Có hằng số cố định nào chặn tỷ số đó mãi không?"], solution: "Khẳng định sai. Tỷ số (2/1.99)ⁿ tăng không bị chặn, nên không tồn tại c sao cho 2ⁿ ≤ c·1.99ⁿ với mọi n đủ lớn.", explanation: "Có thể bỏ hệ số nhân hằng, nhưng đổi cơ số hàm mũ làm đổi tốc độ tăng tiệm cận.", relatedTopicIds: ["complexity-analysis"], estimatedMinutes: 18 },
    { type: "further-reading", id: "reading", title: "Đọc thêm", sourceIds: ["clrs-4e"], body: "Đọc các chương về ký hiệu tiệm cận và truy hồi để nắm định nghĩa hình thức, rồi quay lại các chương phân tích trong khi tự lần theo thuật toán cụ thể." },
  ],
};

const gradientDescent: DeepTopicTranslation = {
  objectives: objectives("gradient-descent", ["Diễn giải gradient như hướng tăng nhanh nhất tại một điểm.", "Suy ra cập nhật hạ dốc từ xấp xỉ bậc nhất.", "Lần theo tối ưu hóa trên hàm bậc hai một biến.", "Giải thích ảnh hưởng của tốc độ học và chuẩn hóa đặc trưng.", "Phân biệt cập nhật batch, stochastic và mini-batch.", "Chẩn đoán phân kỳ, dao động và hội tụ chậm."]),
  glossary: [{ term: "Gradient", definition: "Vector các đạo hàm riêng; theo chuẩn Euclid, nó chỉ hướng tăng cục bộ nhanh nhất." }, { term: "Tốc độ học", definition: "Tham số bước dương điều khiển quãng di chuyển theo hướng ngược gradient." }, { term: "Điều kiện hóa", definition: "Mức độ độ cong của hàm mục tiêu không đều theo các hướng; điều kiện hóa kém làm tối ưu bậc nhất chậm." }],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Mục tiêu học tập", objectives: ["Suy ra quy tắc cập nhật", "Tính gradient bằng tay", "Chọn và chẩn đoán tốc độ học", "Liên hệ hành vi tối ưu với tỷ lệ và độ cong"] },
    { type: "intuition", id: "intuition", title: "Đi theo độ dốc cục bộ", body: "Tại một điểm khả vi, gradient tóm tắt độ dốc theo mọi tọa độ. Di chuyển một đoạn nhỏ theo hướng ngược lại làm hàm giảm nhanh nhất trong số các bước Euclid có cùng độ dài.", analogy: "Hãy tưởng tượng đứng trên sườn đồi trơn trong sương mù. Gradient là mũi tên lên dốc dưới chân; quay ngược lại để đi xuống." },
    { type: "formula", id: "update-rule", title: "Quy tắc cập nhật", expression: "θₜ₊₁ = θₜ − η∇J(θₜ)", description: "Mỗi vòng lặp tính gradient của hàm mục tiêu tại tham số hiện tại rồi bước theo hướng âm của gradient.", terms: [{ symbol: "θₜ", meaning: "Vector tham số tại vòng lặp t" }, { symbol: "η", meaning: "Tốc độ học" }, { symbol: "J", meaning: "Hàm mục tiêu hoặc hàm mất mát" }, { symbol: "∇J(θₜ)", meaning: "Gradient tại tham số hiện tại" }], citations: [{ sourceId: "mml-book", locator: "Chương 7" }] },
    { type: "derivation", id: "derivation", title: "Suy ra bước đi từ tuyến tính hóa cục bộ", introduction: "Xấp xỉ Taylor bậc nhất dự đoán hàm mục tiêu thay đổi thế nào với dịch chuyển nhỏ Δ.", steps: [{ expression: "J(θ + Δ) ≈ J(θ) + ∇J(θ)ᵀΔ", explanation: "Cục bộ, hàm mục tiêu được xấp xỉ bằng một siêu phẳng." }, { expression: "minimize ∇J(θ)ᵀΔ subject to ‖Δ‖₂ ≤ η‖∇J(θ)‖₂", explanation: "Chọn bước bị chặn làm thay đổi dự đoán âm nhất." }, { expression: "Δ = −η∇J(θ)", explanation: "Theo bất đẳng thức Cauchy–Schwarz, tích vô hướng âm nhất xuất hiện ở hướng ngược gradient." }], conclusion: "Hạ dốc là phương pháp cục bộ: xấp xỉ tuyến tính biện minh cho hướng đi, còn η quyết định bước có còn đáng tin hay không." },
    { type: "worked-example", id: "quadratic-example", title: "Ví dụ: cực tiểu hàm bậc hai một biến", problem: "Cực tiểu J(θ) = (θ − 3)² từ θ₀ = 0 với η = 0.25.", steps: [{ title: "Lấy đạo hàm", explanation: "Đạo hàm bằng hai lần khoảng cách tới điểm cực tiểu.", formula: "J′(θ) = 2(θ − 3)" }, { title: "Cập nhật lần một", explanation: "Tại θ₀ = 0, đạo hàm bằng −6.", formula: "θ₁ = 0 − 0.25(−6) = 1.5" }, { title: "Cập nhật lần hai", explanation: "Tại θ₁ = 1.5, đạo hàm bằng −3.", formula: "θ₂ = 1.5 − 0.25(−3) = 2.25" }, { title: "Quan sát co lại", explanation: "Mỗi bước giảm một nửa khoảng cách còn lại tới 3.", formula: "3 − θₜ₊₁ = 0.5(3 − θₜ)" }], conclusion: "Dãy 0, 1.5, 2.25, 2.625, … hội tụ theo cấp số nhân tới điểm cực tiểu 3." },
    { type: "worked-example", id: "learning-rate-example", title: "Ví dụ: bước đi quá lớn", problem: "Vẫn dùng J(θ) = (θ − 3)² nhưng chọn η = 1.1.", steps: [{ title: "Viết cập nhật sai số", explanation: "Đặt eₜ = θₜ − 3 để tách hành vi hội tụ.", formula: "eₜ₊₁ = (1 − 2η)eₜ" }, { title: "Thay η", explanation: "Hệ số nhân là −1.2.", formula: "eₜ₊₁ = −1.2eₜ" }, { title: "Diễn giải", explanation: "Dấu đổi ở mỗi vòng và độ lớn tăng 20%." }], conclusion: "Hướng có thể đúng nhưng độ dài bước vẫn phá hỏng quá trình. Hạ dốc phân kỳ trong trường hợp này." },
    { type: "comparison", id: "variants", title: "Các biến thể cập nhật", columns: ["Ước lượng gradient", "Điểm mạnh", "Đánh đổi"], rows: [{ label: "Batch", values: ["Toàn bộ mẫu huấn luyện", "Ổn định và xác định", "Mỗi cập nhật tốn kém"] }, { label: "Stochastic", values: ["Một mẫu", "Cập nhật thường xuyên", "Phương sai cao"] }, { label: "Mini-batch", values: ["Một lô nhỏ", "Tận dụng phần cứng tốt", "Phải chọn kích thước lô"] }] },
    { type: "code", id: "implementation", title: "Cài đặt tham chiếu", language: "python", code: "def gradient_descent(gradient, initial, learning_rate=0.1, steps=100):\n    theta = initial\n    history = [theta]\n    for _ in range(steps):\n        theta = theta - learning_rate * gradient(theta)\n        history.append(theta)\n    return theta, history", explanation: [{ lines: "1", body: "Nhận gradient như một hàm để bộ tối ưu không phụ thuộc một hàm mục tiêu cụ thể." }, { lines: "2–3", body: "Giữ tham số hiện tại và lịch sử phục vụ chẩn đoán hội tụ." }, { lines: "4–6", body: "Áp dụng đúng một cập nhật trạng thái mỗi vòng." }, { lines: "7", body: "Trả cả giá trị cuối và dấu vết; cần quan sát quá trình tối ưu, không chỉ chạy nó." }] },
    { type: "callout", id: "scaling", title: "Chuẩn hóa đặc trưng làm đổi hình học", tone: "insight", body: "Khi một đặc trưng có miền hàng nghìn còn đặc trưng khác chỉ là phần nhỏ, đường đồng mức bị kéo dài. Một tốc độ học sẽ dao động ở hướng dốc nhưng bò chậm ở hướng thoải. Chuẩn hóa thường cải thiện điều kiện hóa." },
    { type: "common-mistakes", id: "mistakes", title: "Lỗi thường gặp", mistakes: [{ mistake: "Xem loss huấn luyện giảm là bằng chứng tổng quát hóa", consequence: "Tối ưu thành công bị nhầm với chất lượng trên dữ liệu chưa thấy.", correction: "Theo dõi validation tách biệt với mục tiêu tối ưu." }, { mistake: "Dùng một tốc độ học mà không xem dấu vết", consequence: "Hội tụ chậm hoặc phân kỳ không được phát hiện.", correction: "Vẽ loss và chuẩn gradient; thử tốc độ theo thang logarithm." }, { mistake: "Chỉ dừng theo số vòng cố định", consequence: "Có thể dừng quá sớm hoặc lãng phí tính toán.", correction: "Xét thêm thay đổi mục tiêu, chuẩn gradient hoặc dừng theo validation." }] },
    { type: "exercise", id: "ex-update", title: "Bài tập: hai bước cập nhật", exerciseType: "calculation", difficulty: "easy", prompt: "Với J(θ) = θ² + 4θ, bắt đầu θ₀ = 2 và thực hiện hai cập nhật với η = 0.1.", hints: ["Lấy đạo hàm J trước.", "Mỗi lần dùng θ vừa tính được."], solution: "J′(θ)=2θ+4. θ₁=2−0.1(8)=1.2. θ₂=1.2−0.1(6.4)=0.56.", explanation: "Điểm cực tiểu là −2, nên cả hai cập nhật đều dịch trái về phía nó.", relatedTopicIds: ["gradient-descent", "optimization"], estimatedMinutes: 8 },
    { type: "exercise", id: "ex-rate", title: "Bài tập: khoảng hội tụ", exerciseType: "proof", difficulty: "medium", prompt: "Với J(θ)=aθ²/2, a>0, hãy suy ra khoảng tốc độ học hằng làm hạ dốc hội tụ.", hints: ["Viết θₜ₊₁ như một bội của θₜ.", "Hội tụ đòi hỏi trị tuyệt đối hệ số nhỏ hơn một."], solution: "Gradient là aθ, nên θₜ₊₁=(1−ηa)θₜ. Điều kiện |1−ηa|<1 cho 0<η<2/a.", explanation: "Độ cong a quyết định bước ổn định lớn nhất.", relatedTopicIds: ["gradient-descent", "optimization"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-debug", title: "Bài tập: gỡ lỗi bộ tối ưu", exerciseType: "debugging", difficulty: "hard", prompt: "Loss huấn luyện thành NaN sau vài bước. Hãy đưa ra kế hoạch chẩn đoán theo thứ tự ưu tiên.", hints: ["Bắt đầu từ độ lớn cập nhật.", "Tái hiện giá trị không hữu hạn đầu tiên trước khi sửa."], solution: "Tái hiện bước lỗi đầu tiên; ghi loss, chuẩn gradient, chuẩn tham số và batch. Giảm tốc độ học; kiểm tra đầu vào chưa chuẩn hóa và gradient bùng nổ; xác minh miền của loss như log(0); chỉ dùng phép toán ổn định hay clipping khi dấu vết ủng hộ.", explanation: "Dấu vết theo thời gian thu hẹp nguyên nhân tốt hơn các bản vá phỏng đoán.", relatedTopicIds: ["gradient-descent", "deep-optimization"], estimatedMinutes: 20 },
    { type: "further-reading", id: "reading", title: "Đọc thêm", sourceIds: ["mml-book"], body: "Học tối ưu liên tục sau giải tích vector, rồi nối hình học cập nhật với hồi quy tuyến tính và huấn luyện mạng nơ-ron." },
  ],
};

const linearRegression: DeepTopicTranslation = {
  objectives: objectives("linear-regression", ["Biểu diễn hồi quy tuyến tính bằng ký hiệu vô hướng và ma trận.", "Suy ra bình phương tối thiểu từ mục tiêu sai số bình phương.", "Diễn giải hệ số trong đúng bối cảnh và đơn vị.", "Chọn bộ giải ổn định thay vì nghịch đảo ma trận trực tiếp.", "Xây dựng quy trình đánh giá không rò rỉ dữ liệu.", "Chẩn đoán giả định bằng phần dư và metric phù hợp."]),
  glossary: [{ term: "Phần dư", definition: "Chênh lệch giữa giá trị quan sát và dự đoán: eᵢ = yᵢ − ŷᵢ." }, { term: "Ma trận thiết kế", definition: "Ma trận X có mỗi hàng là một quan sát và mỗi cột là một đặc trưng." }, { term: "Đa cộng tuyến", definition: "Tình trạng các cột đặc trưng phụ thuộc tuyến tính mạnh, làm hệ số khó xác định và kém ổn định." }],
  content: [
    { type: "learning-objectives", id: "objectives", title: "Mục tiêu học tập", objectives: ["Viết mô hình và hàm mục tiêu", "Khớp một đường thẳng bằng tay", "Suy ra phương trình chuẩn", "Xây dựng pipeline không rò rỉ", "Đọc phần dư và giới hạn của hệ số"] },
    { type: "intuition", id: "intuition", title: "Một xấp xỉ tuyến tính toàn cục", body: "Hồi quy tuyến tính chọn mặt phẳng affine có dự đoán gần các mục tiêu quan sát nhất theo sai số bình phương. Mô hình đơn giản, nhưng quy trình quanh nó—định nghĩa đặc trưng, kiểm soát rò rỉ, chẩn đoán phần dư và bất định—thì không.", analogy: "Trong một chiều, hãy hình dung cân bằng các khoảng cách dọc bình phương quanh một đường; sai lệch lớn kéo mạnh hơn vì bị bình phương." },
    { type: "formula", id: "model", title: "Mô hình và hàm mục tiêu", expression: "ŷ = Xw + b1,   J(w,b) = (1/n)‖y − ŷ‖²₂", description: "Dự đoán tuyến tính theo tham số. Mất mát bình phương đo sai lệch dọc trung bình và tạo ra hàm mục tiêu lồi, khả vi.", terms: [{ symbol: "X ∈ ℝⁿˣᵈ", meaning: "Ma trận thiết kế gồm n quan sát và d đặc trưng" }, { symbol: "w ∈ ℝᵈ", meaning: "Các hệ số đặc trưng" }, { symbol: "b", meaning: "Hệ số chặn" }, { symbol: "y", meaning: "Các mục tiêu quan sát" }], citations: [{ sourceId: "mml-book", locator: "Chương 9" }, { sourceId: "isl", locator: "Hồi quy tuyến tính" }] },
    { type: "worked-example", id: "fit-line", title: "Ví dụ: khớp đường thẳng bằng tay", problem: "Khớp y = wx + b cho các điểm (1,2), (2,3) và (3,5).", steps: [{ title: "Tính trung bình", explanation: "Đường thẳng đi qua trung bình mẫu.", formula: "x̄=2, ȳ=10/3" }, { title: "Tính độ dốc", explanation: "Chia tổng tích chéo đã chuẩn tâm cho tổng bình phương x đã chuẩn tâm.", formula: "w = Σ(xᵢ−x̄)(yᵢ−ȳ) / Σ(xᵢ−x̄)² = 3/2" }, { title: "Tính hệ số chặn", explanation: "Dùng b = ȳ − wx̄.", formula: "b = 10/3 − 3 = 1/3" }, { title: "Kiểm tra phần dư", explanation: "Dự đoán là 11/6, 10/3 và 29/6; phần dư có tổng bằng không khi mô hình có hệ số chặn." }], conclusion: "Đường khớp là ŷ = 1.5x + 0.333. Tập nhỏ khiến mọi giả định dễ quan sát." },
    { type: "derivation", id: "normal-equation", title: "Suy ra phương trình chuẩn", introduction: "Gộp hệ số chặn vào X bằng một cột toàn 1 và cực tiểu chuẩn bình phương chưa chia tỷ lệ.", steps: [{ expression: "J(w) = (y − Xw)ᵀ(y − Xw)", explanation: "Viết sai số bình phương dưới dạng tích vô hướng." }, { expression: "∇J(w) = −2Xᵀ(y − Xw)", explanation: "Lấy đạo hàm biểu thức bậc hai theo w." }, { expression: "XᵀXw = Xᵀy", explanation: "Cho gradient bằng không tại điểm dừng." }, { expression: "ŵ = (XᵀX)⁻¹Xᵀy", explanation: "Dạng này cần XᵀX khả nghịch; bộ giải thực tế ưu tiên QR hoặc SVD hơn là tạo nghịch đảo." }], conclusion: "Hàm mục tiêu lồi nên mọi nghiệm của phương trình chuẩn đều tối ưu toàn cục. Thiếu hạng có thể khiến nghiệm không duy nhất." },
    { type: "code", id: "implementation", title: "Cài đặt NumPy với bình phương tối thiểu ổn định", language: "python", code: "import numpy as np\n\ndef fit_linear_regression(X, y):\n    X = np.asarray(X, dtype=float)\n    y = np.asarray(y, dtype=float)\n    design = np.column_stack([np.ones(len(X)), X])\n    coefficients, *_ = np.linalg.lstsq(design, y, rcond=None)\n    return coefficients[0], coefficients[1:]\n\ndef predict(X, intercept, weights):\n    return np.asarray(X, dtype=float) @ weights + intercept", explanation: [{ lines: "4–5", body: "Chuẩn hóa kiểu đầu vào và phát hiện lỗi kích thước sớm." }, { lines: "6", body: "Thêm cột hệ số chặn một cách tường minh." }, { lines: "7", body: "Dùng bộ giải dựa trên phân rã ma trận ổn định thay vì nghịch đảo XᵀX." }, { lines: "10–11", body: "Tách dự đoán khỏi khớp để đánh giá trên dữ liệu chưa dùng." }], citations: [{ sourceId: "mml-book", locator: "Chương 9" }] },
    { type: "comparison", id: "solvers", title: "Nghiệm đóng và phương pháp gradient", columns: ["Phù hợp nhất", "Điểm mạnh", "Giới hạn"], rows: [{ label: "Bình phương tối thiểu QR/SVD", values: ["Bài toán đặc nhỏ hoặc vừa", "Ổn định, không cần tốc độ học", "Chi phí phân rã tăng theo số đặc trưng"] }, { label: "Hạ dốc batch", values: ["Hàm mục tiêu khả vi lớn", "Đơn giản, dễ mở rộng", "Nhạy với tỷ lệ và kích thước bước"] }, { label: "Tối ưu stochastic", values: ["Dữ liệu rất lớn hoặc streaming", "Cập nhật rẻ và thường xuyên", "Hội tụ nhiễu"] }] },
    { type: "callout", id: "interpretation", title: "Dự đoán không phải quan hệ nhân quả", tone: "warning", body: "Hệ số mô tả liên hệ có điều kiện trong tập đặc trưng đã khớp. Nhiễu do biến ẩn, thiên lệch chọn mẫu, sai số đo và can thiệp cần các giả định nhân quả bổ sung mà bình phương tối thiểu không cung cấp." },
    { type: "step-by-step", id: "workflow", title: "Quy trình không rò rỉ dữ liệu", steps: [{ title: "Định nghĩa đơn vị dự đoán", body: "Nêu một hàng biểu diễn gì và thông tin nào có tại thời điểm dự đoán." }, { title: "Dành riêng dữ liệu đánh giá", body: "Chia dữ liệu trước khi khớp scaler, imputer, encoder hoặc chọn đặc trưng." }, { title: "Tạo baseline", body: "So với dự đoán trung bình tập huấn luyện hoặc quy tắc ngây thơ phù hợp miền." }, { title: "Khớp pipeline", body: "Chỉ ước lượng tham số tiền xử lý trên từng fold huấn luyện." }, { title: "Kiểm tra phần dư", body: "Tìm độ cong, phương sai thay đổi, lỗi theo nhóm, điểm ảnh hưởng và cấu trúc thời gian." }, { title: "Báo cáo bất định", body: "Đưa ra biến thiên giữa các fold hoặc khoảng ước lượng khi quyết định cần." }] },
    { type: "complexity", id: "complexity", title: "Chi phí tính toán", time: "Tùy bộ giải; bình phương tối thiểu đặc thường là O(nd² + d³)", space: "O(nd) để lưu ma trận thiết kế", analysis: "Khi n lớn hơn d nhiều, tích lũy tích chéo hoặc dùng bộ giải lặp có thể giảm bộ nhớ. Tính thưa làm thay đổi cả lưu trữ lẫn lựa chọn bộ giải.", cases: [{ name: "Dự đoán", complexity: "O(nd)", reason: "Một tích vô hướng cho mỗi quan sát" }, { name: "Một bước gradient", complexity: "O(nd)", reason: "Tính dự đoán và Xᵀ nhân phần dư" }] },
    { type: "common-mistakes", id: "mistakes", title: "Lỗi thường gặp", mistakes: [{ mistake: "Khớp tiền xử lý trước khi chia dữ liệu", consequence: "Validation ảnh hưởng biểu diễn huấn luyện, khiến kết quả lạc quan giả.", correction: "Khớp mọi phép biến đổi học được bên trong pipeline chỉ dùng dữ liệu huấn luyện." }, { mistake: "Xem hệ số lớn là đặc trưng quan trọng", consequence: "Đơn vị, tương quan và mã hóa làm sai lệch độ lớn hệ số.", correction: "Diễn giải trong bối cảnh và dùng đơn vị chuẩn hóa hoặc có ý nghĩa miền." }, { mistake: "Chỉ đánh giá bằng R²", consequence: "Lỗi phần dư có hệ thống hoặc sai số tuyệt đối không chấp nhận được bị che khuất.", correction: "Dùng metric gắn với quyết định và chẩn đoán phần dư." }] },
    { type: "exercise", id: "ex-predict", title: "Bài tập: dự đoán và phần dư", exerciseType: "calculation", difficulty: "easy", prompt: "Với ŷ = 2x − 1 và các quan sát (1,2), (2,2), (4,8), hãy tính dự đoán, phần dư và MSE.", hints: ["Phần dư là quan sát trừ dự đoán.", "Bình phương từng phần dư trước khi lấy trung bình."], solution: "Dự đoán là 1, 3, 7. Phần dư là 1, −1, 1. MSE=(1+1+1)/3=1.", explanation: "Dấu phần dư cho biết hướng; MSE bỏ dấu và phạt độ lớn.", relatedTopicIds: ["linear-regression", "regression-losses"], estimatedMinutes: 8 },
    { type: "exercise", id: "ex-leakage", title: "Bài tập: tìm rò rỉ", exerciseType: "debugging", difficulty: "medium", prompt: "Một nhóm chuẩn hóa toàn bộ dữ liệu, chọn đặc trưng bằng mọi target rồi mới cross-validation. Hãy tìm từng đường rò rỉ và thiết kế lại.", hints: ["Thao tác nào đã học từ hàng bị giữ lại?", "Đặt phép biến đổi học được vào trong từng fold."], solution: "Cả thống kê chuẩn hóa và chọn đặc trưng theo target đều dùng fold validation. Hãy chia trước, rồi khớp scaling và selection trong pipeline riêng trên từng fold huấn luyện; giữ một test cuối hoàn toàn chưa đụng tới.", explanation: "Cross-validation chỉ hợp lệ khi mọi thao tác học được đều lặp lại trong phân vùng huấn luyện.", relatedTopicIds: ["linear-regression", "model-evaluation", "feature-processing"], estimatedMinutes: 15 },
    { type: "exercise", id: "ex-rank", title: "Bài tập: thiếu hạng", exerciseType: "conceptual", difficulty: "hard", prompt: "Ma trận thiết kế có tuổi theo năm, tuổi theo tháng và hệ số chặn. Hãy giải thích vấn đề số học và diễn giải.", hints: ["Một cột là bội chính xác của cột kia.", "Xét XᵀX có khả nghịch không."], solution: "Tuổi theo tháng bằng 12 lần tuổi theo năm, nên các cột phụ thuộc tuyến tính. X không đủ hạng cột, XᵀX suy biến và vô số cặp hệ số tạo cùng dự đoán. Bỏ một đặc trưng thừa hoặc dùng regularization và diễn giải thận trọng.", explanation: "Vẫn có thể dự đoán dù từng hệ số không thể định danh riêng." , relatedTopicIds: ["linear-regression", "linear-algebra"], estimatedMinutes: 18 },
    { type: "applications", id: "applications", title: "Khi hồi quy tuyến tính hữu ích", applications: [{ name: "Baseline dễ diễn giải", description: "Kiểm tra mô hình phi tuyến có thêm giá trị ngoài quan hệ cộng tuyến tính minh bạch hay không." }, { name: "Hiệu chuẩn và ước lượng xu hướng", description: "Ước lượng quan hệ tuyến tính có hệ thống khi các giả định có thể bảo vệ." }, { name: "Thành phần cục bộ", description: "Dùng mô hình tuyến tính trong pipeline lớn hơn, hiệu chỉnh phần dư và mô hình tuyến tính tổng quát." }] },
    { type: "further-reading", id: "reading", title: "Đọc thêm", sourceIds: ["mml-book", "isl", "sklearn-guide"], body: "Đọc song song một suy dẫn toán học, một cách nhìn học thống kê và hướng dẫn triển khai; mỗi nguồn trả lời một phần khác nhau của bài toán mô hình hóa." },
  ],
};

export const deepTopicTranslationsVi: Record<string, DeepTopicTranslation> = {
  "complexity-analysis": complexity,
  "gradient-descent": gradientDescent,
  "linear-regression": linearRegression,
};
