import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowRight, CheckCircle2 } from "lucide-react";
import { algorithmById, algorithmBySlug, algorithms, topicById } from "@/content";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { BookmarkButton, StatusSelect } from "@/components/content-actions";
import { AlgorithmVisualizer } from "@/components/algorithm-visualizer";
import { Message } from "@/components/locale-provider";
import { LibraryResources } from "@/components/library/library-resources";
import { RelatedPractice } from "@/components/practice/related-practice";

export function generateStaticParams() { return algorithms.map((algorithm) => ({ algorithm: algorithm.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ algorithm: string }> }) { const { algorithm } = await params; const item = algorithmBySlug.get(algorithm); return { title: item?.name ?? "Algorithm", description: item?.summary }; }
export default async function AlgorithmPage({ params }: { params: Promise<{ algorithm: string }> }) {
  const { algorithm: slug } = await params; const item = algorithmBySlug.get(slug); if (!item) notFound();
  return <div className="page narrow"><Breadcrumbs items={[{ label: "Algorithms", href: "/algorithms" }, { label: item.category }, { label: item.name }]} /><header className="page-header"><div><p className="kicker">{item.category} · <Message k="navigation.algorithms" /></p><h1>{item.name}</h1><p className="lede" lang="en">{item.summary}</p></div><div className="header-actions"><StatusSelect id={`algorithm:${item.id}`} /><BookmarkButton bookmark={{ id: item.id, type: "algorithm", title: item.name, href: `/algorithms/${item.slug}`, context: item.category }} /></div></header>
  <div className="doc-layout"><article className="doc-article" lang="en"><section className="doc-section" id="intuition"><h2><Message k="common.intuition" /></h2><p>{item.intuition}</p></section><section className="doc-section" id="complexity"><h2><Message k="common.complexity" /></h2><div className="complexity-grid"><div className="complexity-card"><span><Message k="common.time" /></span><strong>{item.timeComplexity}</strong></div><div className="complexity-card"><span><Message k="common.space" /></span><strong>{item.spaceComplexity}</strong></div></div></section>{item.visualizer && <AlgorithmVisualizer type={item.visualizer} />}<section className="doc-section" id="pseudocode"><h2><Message k="common.pseudocode" /></h2><pre className="code-block"><code>{item.pseudocode}</code></pre></section><section className="doc-section" id="implementation"><h2>Python · <Message k="common.implementation" /></h2><pre className="code-block"><code>{item.python}</code></pre></section><section className="doc-section" id="prerequisites"><h2><Message k="common.prerequisites" /></h2><div className="topic-list">{item.prerequisiteIds.map((id) => { const topic=topicById.get(id); return topic?<Link className="topic-row" href={`/topics/${topic.slug}`} key={id}><span>{topic.title}</span><ArrowRight size={13}/></Link>:null })}</div></section><section className="doc-section" id="mistakes"><h2><Message k="common.commonMistakes" /></h2><ul className="list-clean">{item.mistakes.map((mistake)=><li key={mistake}><AlertTriangle size={15} style={{color:"var(--warning)"}}/>{mistake}</li>)}</ul></section><section className="doc-section" id="uses"><h2><Message k="common.useCases" /></h2><ul className="list-clean">{item.useCases.map((use)=><li key={use}><CheckCircle2 size={15}/>{use}</li>)}</ul></section><RelatedPractice entityType="algorithm" entityId={item.id} /><LibraryResources entityType="algorithm" entityId={item.id} />{item.relatedIds.length>0&&<section className="doc-section" id="related"><h2><Message k="common.relatedAlgorithms" /></h2><div className="topic-list">{item.relatedIds.map((id)=>{const related=algorithmById.get(id);return related?<Link className="topic-row" href={`/algorithms/${related.slug}`} key={id}><span>{related.name}</span><ArrowRight size={13}/></Link>:null})}</div></section>}</article><aside className="doc-aside"><p className="eyebrow" style={{padding:0}}><Message k="common.onThisPage" /></p><nav className="toc">{[{label:"Intuition",id:"intuition"},{label:"Complexity",id:"complexity"},...(item.visualizer?[{label:"Visualization",id:"visualization"}]:[]),{label:"Pseudocode",id:"pseudocode"},{label:"Implementation",id:"implementation"},{label:"Prerequisites",id:"prerequisites"},{label:"Mistakes",id:"mistakes"},{label:"Use cases",id:"uses"}].map((entry)=><a key={entry.id} href={`#${entry.id}`}>{entry.label}</a>)}</nav></aside></div></div>;
}
